# Generated by Django 5.0.6 on 2025-01-10 06:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='avatars/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('businessId', models.AutoField(primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=100)),
                ('businessType', models.CharField(choices=[('individual', 'Individual Teacher'), ('school', 'School'), ('studio', 'Studio'), ('academy', 'Academy'), ('center', 'Learning Center')], max_length=50)),
                ('businessDescription', models.TextField(max_length=500)),
                ('businessImage', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='business_images/')),
                ('openingTime', models.TimeField()),
                ('closingTime', models.TimeField()),
                ('cancellationPolicy', models.CharField(choices=[('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('flexible', 'Flexible')], max_length=20)),
                ('liabilityWaiver', models.BooleanField(default=False)),
                ('studentContactPhone', models.CharField(max_length=100)),
                ('studentContactEmail', models.EmailField(max_length=254)),
                ('adminContactPhone', models.CharField(blank=True, max_length=100, null=True)),
                ('adminContactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferredContact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both Email and Phone')], max_length=20)),
                ('businessAddress', models.CharField(max_length=255)),
                ('businessCity', models.CharField(max_length=100)),
                ('businessState', models.CharField(max_length=100)),
                ('businessZipCode', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('showExactLocation', models.BooleanField(default=False)),
                ('classCategory', models.CharField(choices=[('academic', 'Academic'), ('music', 'Music'), ('dance', 'Dance'), ('fitness', 'Fitness'), ('art', 'Art'), ('technology', 'Technology'), ('sports', 'Sports')], max_length=50)),
                ('subcategories', models.CharField(max_length=255)),
                ('classFormats', models.CharField(max_length=255)),
                ('skillLevels', models.CharField(max_length=255)),
                ('ageGroups', models.CharField(max_length=255)),
                ('verificationDocument', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='verification_documents/')),
                ('verificationStatus', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('termsAccepted', models.BooleanField(default=False)),
                ('privacyAccepted', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('totalReviews', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_businesses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Information',
                'db_table': 'business_info',
            },
        ),
        migrations.CreateModel(
            name='ClassesMain',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('features', models.JSONField(default=list)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=50)),
                ('saltLocation', models.BooleanField(default=False)),
                ('studentContactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('studentContactPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('adminContactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('adminContactPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('businessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='quickstart.classesmain'),
        ),
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='class_images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quickstart.classesmain')),
            ],
            options={
                'db_table': 'class_images',
            },
        ),
        migrations.CreateModel(
            name='ClassOption',
            fields=[
                ('optionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[('single', 'Single Session'), ('course', 'Full Course'), ('recurring', 'Recurring Classes')], default='single', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='class_options/')),
                ('duration', models.IntegerField(default=60)),
                ('maxParticipants', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_type', models.CharField(choices=[('per_session', 'Per Session'), ('per_month', 'Monthly'), ('full_course', 'Full Course')], default='per_session', max_length=20)),
                ('total_sessions', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('sessions_per_week', models.IntegerField(blank=True, null=True)),
                ('auto_renew_default', models.BooleanField(default=False)),
                ('equipment', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('cancellationPolicy', models.CharField(choices=[('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('flexible', 'Flexible')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quickstart.classesmain')),
            ],
            options={
                'db_table': 'class_options',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoriteId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('active_classes', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('performance_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='quickstart.businessinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='quickstart.instructor')),
            ],
            options={
                'db_table': 'instructor_education',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='quickstart.instructor')),
            ],
            options={
                'db_table': 'instructor_certifications',
            },
        ),
        migrations.CreateModel(
            name='InstructorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='quickstart.instructor')),
            ],
            options={
                'db_table': 'instructor_notes',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('businessId', models.ForeignKey(blank=True, db_column='businessId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.businessinfo')),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.role'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('time', models.TimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Override price for this schedule. If not set, uses ClassOption default price', max_digits=10, null=True)),
                ('maxParticipants', models.IntegerField(blank=True, help_text='Override max participants for this schedule. If not set, uses ClassOption default', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='quickstart.classoption')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['day', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='quickstart.instructor')),
            ],
            options={
                'db_table': 'instructor_skills',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('grade_level', models.CharField(max_length=20)),
                ('parent_guardian_name', models.CharField(max_length=100)),
                ('parent_guardian_phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('active_classes', models.IntegerField(default=0)),
                ('total_classes_taken', models.IntegerField(default=0)),
                ('average_attendance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overall_performance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='quickstart.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='quickstart.student')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='quickstart.student')),
            ],
            options={
                'db_table': 'student_notes',
            },
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['businessType'], name='business_in_busines_450d26_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['classCategory'], name='business_in_classCa_d3ac0a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['isActive'], name='business_in_isActiv_911d84_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['option', 'day', 'time'], name='schedules_option__543303_idx'),
        ),
    ]
