# Generated by Django 4.1.3 on 2024-06-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('businessName', models.CharField(max_length=100)),
                ('businessId', models.AutoField(primary_key=True, serialize=False)),
                ('businessType', models.CharField(max_length=100)),
                ('businessAddress', models.CharField(max_length=100)),
                ('businessDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('businessCity', models.CharField(max_length=100)),
                ('businessState', models.CharField(blank=True, max_length=100, null=True)),
                ('businessPhoneNumber', models.CharField(max_length=100)),
                ('businessEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField()),
                ('businessDefaultCancellation', models.CharField(blank=True, max_length=100, null=True)),
                ('businessZipCode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'businessInfo',
            },
        ),
        migrations.CreateModel(
            name='ClassesMain',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=100)),
                ('classDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('classLocation', models.CharField(max_length=100)),
                ('classRating', models.CharField(max_length=100)),
                ('classCategory', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('businessId', models.ForeignKey(blank=True, db_column='businessId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'classesMain',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SubClasses',
            fields=[
                ('subclassId', models.AutoField(primary_key=True, serialize=False)),
                ('subclassTitle', models.CharField(max_length=100)),
                ('subclassDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('subclassType', models.CharField(max_length=100)),
                ('subclassPrice', models.IntegerField()),
                ('subclassCategory', models.CharField(max_length=100)),
                ('subclassCalenderDuration', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
            ],
            options={
                'db_table': 'subClasses',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('availableSlots', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('subclassId', models.ForeignKey(blank=True, db_column='subclassId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.subclasses')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField()),
                ('businessId', models.ForeignKey(blank=True, db_column='businessId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.businessinfo')),
                ('userId', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.users')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoriteId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
                ('userId', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.users')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollmentId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('scheduleId', models.ForeignKey(blank=True, db_column='scheduleId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.schedules')),
                ('userId', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.users')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='userId',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.users'),
        ),
    ]
