# Generated by Django 5.0.6 on 2024-08-14 23:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('availableSlots', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('businessName', models.CharField(max_length=100)),
                ('businessId', models.AutoField(primary_key=True, serialize=False)),
                ('businessImage', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='business_images/')),
                ('businessType', models.CharField(max_length=100)),
                ('businessAddress', models.CharField(max_length=100)),
                ('businessDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('businessCity', models.CharField(max_length=100)),
                ('businessState', models.CharField(blank=True, max_length=100, null=True)),
                ('businessPhoneNumber', models.CharField(max_length=100)),
                ('businessEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('businessDefaultCancellation', models.CharField(blank=True, max_length=100, null=True)),
                ('businessZipCode', models.CharField(max_length=100)),
                ('totalReviews', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businessInfo',
            },
        ),
        migrations.CreateModel(
            name='ClassesMain',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=50)),
                ('classDescription', models.CharField(blank=True, max_length=2000, null=True)),
                ('classLocation', models.CharField(max_length=100)),
                ('classCoordinates', models.CharField(max_length=100)),
                ('classRating', models.CharField(max_length=100)),
                ('classFeatures', models.CharField(max_length=1000)),
                ('classPrice', models.IntegerField()),
                ('classCategory', models.CharField(max_length=100)),
                ('classFilterCategory', models.CharField(max_length=100)),
                ('classFilterSubcategory', models.CharField(max_length=100)),
                ('classTotalReviews', models.IntegerField()),
                ('additionalInfo', models.CharField(blank=True, max_length=5000, null=True)),
                ('createdAt', models.DateTimeField()),
                ('businessId', models.ForeignKey(blank=True, db_column='businessId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'classesMain',
            },
        ),
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='class_images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quickstart.classesmain')),
            ],
            options={
                'db_table': 'classImages',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoriteId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('businessId', models.ForeignKey(blank=True, db_column='businessId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.businessinfo')),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollmentId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('scheduleId', models.ForeignKey(blank=True, db_column='scheduleId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.schedules')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='SubClasses',
            fields=[
                ('subclassId', models.AutoField(primary_key=True, serialize=False)),
                ('subclassTitle', models.CharField(max_length=100)),
                ('subclassDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('subclassImage', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='subclass_images/')),
                ('subclassTags', models.CharField(max_length=100)),
                ('subclassType', models.CharField(max_length=100)),
                ('subclassLevel', models.CharField(max_length=100)),
                ('subclassAvailability', models.IntegerField()),
                ('subclassPrice', models.IntegerField()),
                ('subclassCategory', models.CharField(max_length=100)),
                ('subclassCalenderDuration', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('classId', models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain')),
            ],
            options={
                'db_table': 'subClasses',
            },
        ),
        migrations.AddField(
            model_name='schedules',
            name='subclassId',
            field=models.ForeignKey(blank=True, db_column='subclassId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.subclasses'),
        ),
    ]
