# Generated by Django 4.1.3 on 2024-06-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='classPrice',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
