# Generated by Django 5.0.6 on 2024-08-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollments',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='userId',
        ),
    ]
