# Generated by Django 5.0.6 on 2024-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoption',
            name='cancellationPolicy',
            field=models.CharField(choices=[('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('flexible', 'Flexible')], max_length=30),
        ),
    ]
