# Generated by Django 5.0.6 on 2024-12-20 09:01

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model('quickstart', 'Role')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Define roles and their permissions
    roles_data = {
        'Student': [
            ('view_customuser', 'quickstart', 'customuser'),
            ('view_classesmain', 'quickstart', 'classesmain'),
        ],
        'Instructor': [
            ('view_customuser', 'quickstart', 'customuser'),
            ('view_classesmain', 'quickstart', 'classesmain'),
            ('change_classesmain', 'quickstart', 'classesmain'),
            ('view_instructor', 'quickstart', 'instructor'),
            ('change_instructor', 'quickstart', 'instructor'),
        ],
        'Content Creator': [
            ('view_customuser', 'quickstart', 'customuser'),
            ('view_classesmain', 'quickstart', 'classesmain'),
            ('change_classesmain', 'quickstart', 'classesmain'),
            ('add_classesmain', 'quickstart', 'classesmain'),
            ('view_instructor', 'quickstart', 'instructor'),
            ('change_instructor', 'quickstart', 'instructor'),
        ],
        'Manager': [
            ('view_customuser', 'quickstart', 'customuser'),
            ('add_customuser', 'quickstart', 'customuser'),
            ('change_customuser', 'quickstart', 'customuser'),
            ('view_classesmain', 'quickstart', 'classesmain'),
            ('add_classesmain', 'quickstart', 'classesmain'),
            ('change_classesmain', 'quickstart', 'classesmain'),
            ('view_businessinfo', 'quickstart', 'businessinfo'),
            ('change_businessinfo', 'quickstart', 'businessinfo'),
            ('view_instructor', 'quickstart', 'instructor'),
            ('add_instructor', 'quickstart', 'instructor'),
            ('change_instructor', 'quickstart', 'instructor'),
        ],
        'Business Owner': [
            ('view_customuser', 'quickstart', 'customuser'),
            ('add_customuser', 'quickstart', 'customuser'),
            ('change_customuser', 'quickstart', 'customuser'),
            ('view_classesmain', 'quickstart', 'classesmain'),
            ('add_classesmain', 'quickstart', 'classesmain'),
            ('change_classesmain', 'quickstart', 'classesmain'),
            ('view_businessinfo', 'quickstart', 'businessinfo'),
            ('add_businessinfo', 'quickstart', 'businessinfo'),
            ('change_businessinfo', 'quickstart', 'businessinfo'),
            ('delete_businessinfo', 'quickstart', 'businessinfo'),
            ('view_instructor', 'quickstart', 'instructor'),
            ('add_instructor', 'quickstart', 'instructor'),
            ('change_instructor', 'quickstart', 'instructor'),
        ],
    }

    # Create roles
    for role_name, permissions in roles_data.items():
        role = Role.objects.create(name=role_name)
        
        # Add specific permissions
        for codename, app_label, model in permissions:
            try:
                content_type = ContentType.objects.get(
                    app_label=app_label,
                    model=model
                )
                permission = Permission.objects.get(
                    codename=codename,
                    content_type=content_type
                )
                role.permissions.add(permission)
            except (ContentType.DoesNotExist, Permission.DoesNotExist):
                print(f"Permission {codename} for {app_label}.{model} not found")

    # Create Admin and Super Admin roles with all permissions
    for admin_role in ['Admin', 'Super Admin']:
        role = Role.objects.create(name=admin_role)
        all_permissions = Permission.objects.all()
        role.permissions.set(all_permissions)


def remove_roles(apps, schema_editor):
    Role = apps.get_model('quickstart', 'Role')
    Role.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('quickstart', '0002_alter_classoption_cancellationpolicy'),
    ]

    operations = [
        migrations.RunPython(create_roles, remove_roles),
    ]