# Generated by Django 5.0.6 on 2024-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_classesmain_classprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='classTotalReviews',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
    ]
