# Generated by Django 5.0.6 on 2025-01-14 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='quickstart.schedule')),
            ],
            options={
                'db_table': 'schedule_breaks',
            },
        ),
        migrations.CreateModel(
            name='ScheduleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_participants', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('attendance_marked', models.BooleanField(default=False)),
                ('instructor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='quickstart.schedule')),
            ],
            options={
                'db_table': 'schedule_instances',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='quickstart.student')),
                ('schedule_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='quickstart.scheduleinstance')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='quickstart.scheduleinstance'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['schedule_instance', 'status'], name='bookings_schedul_3bb8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', 'status'], name='bookings_student_5b9171_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulebreak',
            index=models.Index(fields=['schedule', 'start_date', 'end_date'], name='schedule_br_schedul_5fe124_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleinstance',
            index=models.Index(fields=['date', 'time'], name='schedule_in_date_7db777_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleinstance',
            index=models.Index(fields=['schedule', 'date'], name='schedule_in_schedul_c46962_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleinstance',
            unique_together={('schedule', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['schedule_instance', 'student'], name='attendance_schedul_c6f8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'marked_at'], name='attendance_status_18416d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('schedule_instance', 'student')},
        ),
    ]
