# Generated by Django 5.0.6 on 2024-08-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_user_enrollments_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
