# Generated by Django 5.0.6 on 2025-01-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_booking_schedule_schedulebreak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active_classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='average_attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='overall_performance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_classes_taken',
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quickstart.classoption')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quickstart.student')),
            ],
            options={
                'db_table': 'student_enrollments',
                'indexes': [models.Index(fields=['student', 'status'], name='student_enr_student_14cdf6_idx'), models.Index(fields=['class_option', 'status'], name='student_enr_class_o_bf85cc_idx')],
            },
        ),
    ]
