# Generated by Django 5.0.6 on 2024-08-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_birthdate_customuser_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
