# Generated by Django 5.0.6 on 2024-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_classesmain_classtotalreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='classFilterCategory',
            field=models.CharField(default='Fitness', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classesmain',
            name='classFilterSubcategory',
            field=models.CharField(default='Martial Arts', max_length=100),
            preserve_default=False,
        ),
    ]
