# Generated by Django 5.0.6 on 2025-01-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_student_active_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendance_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='current_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('single', 'Single Session'), ('course', 'Course Session'), ('recurring', 'Recurring Session')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sessions_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['enrollment_type', 'status'], name='bookings_enrollm_3687e4_idx'),
        ),
    ]
