# Generated by Django 5.0.6 on 2024-06-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_classesmain_classfiltercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclasses',
            name='subclassAvailability',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subclasses',
            name='subclassLevel',
            field=models.CharField(default='Beginner', max_length=100),
            preserve_default=False,
        ),
    ]
