# Generated by Django 5.0.6 on 2025-02-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_booking_attendance_marked_booking_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
