# Generated by Django 5.0.6 on 2024-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_subclasses_subclassavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclasses',
            name='subclassTags',
            field=models.CharField(default='Wheelchair accessible', max_length=100),
            preserve_default=False,
        ),
    ]
