# Generated by Django 5.0.6 on 2025-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_booking_booking_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course'), ('Recurring Classes', 'Recurring Classes')], default='Single Session', max_length=20),
        ),
    ]
