# Generated by Django 5.0.6 on 2024-07-07 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_subclasses_subclasstags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='classId',
            field=models.ForeignKey(blank=True, db_column='classId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.classesmain'),
        ),
    ]
