# Generated by Django 5.0.6 on 2025-02-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_booking_enrollment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
    ]
