# Generated by Django 5.0.6 on 2024-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_reviews_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
