# Generated by Django 5.0.6 on 2024-10-04

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

def create_roles(apps, schema_editor):
    Role = apps.get_model('quickstart', 'Role')
    roles = ['Student', 'Instructor', 'Content Creator', 'Manager', 'Business Owner', 'Admin', 'SuperAdmin']
    for role_name in roles:
        Role.objects.create(name=role_name)

def assign_default_role(apps, schema_editor):
    CustomUser = apps.get_model('quickstart', 'CustomUser')
    Role = apps.get_model('quickstart', 'Role')
    default_role = Role.objects.get(name='Student')
    for user in CustomUser.objects.all():
        user.role = default_role
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quickstart', '0007_instructor_education_certification_instructornote_and_more'),  # Adjust to latest migration number
    ]

    operations = [
        
        # RunPython: Create default roles
        migrations.RunPython(create_roles),
        # RunPython: Assign default role ('Student') to all existing users
        migrations.RunPython(assign_default_role),
    ]
