# Generated by Django 5.0.6 on 2025-02-02 05:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_student_grade_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduleinstance',
            name='schedule_in_date_7db777_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='course_end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sessions_per_week',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_sessions',
        ),
        migrations.RemoveField(
            model_name='scheduleinstance',
            name='attendance_marked',
        ),
        migrations.AddField(
            model_name='scheduleinstance',
            name='capacity_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('single', 'Single Session'), ('recurring', 'Recurring Classes'), ('course', 'Full Course')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='scheduleinstance',
            index=models.Index(fields=['date', 'status'], name='schedule_in_date_9268fb_idx'),
        ),
    ]
