# Generated by Django 5.0.6 on 2024-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_classesmain_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='classFeatures',
            field=models.CharField(default='Accepts credit cards', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='classDescription',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='className',
            field=models.CharField(max_length=50),
        ),
    ]
