# Generated by Django 5.0.6 on 2024-07-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_classesmain_classfeatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='classCoordinates',
            field=models.CharField(default='43.653225,-79.383186', max_length=100),
            preserve_default=False,
        ),
    ]
