# Generated by Django 5.0.6 on 2025-02-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_remove_scheduleinstance_schedule_in_date_7db777_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sessions_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Recurring Classes', 'Recurring Classes'), ('Full Course', 'Full Course')], default='Single Session', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_group_id'], name='bookings_booking_d33ada_idx'),
        ),
    ]
