# Generated by Django 5.0.6 on 2024-10-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_bookingstatus_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='subclassId',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField()),
                ('enrolled_students', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='quickstart.classesmain')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.instructor')),
                ('subclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.subclasses')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='scheduleId',
            field=models.ForeignKey(blank=True, db_column='scheduleId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.schedule'),
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('instructor', 'Instructor Double Booking'), ('room', 'Room Double Booking'), ('student', 'Student Double Booking')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflicting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicting_with', to='quickstart.schedule')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='quickstart.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=20)),
                ('attendance_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quickstart.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'start_time'], name='quickstart__date_07e02c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['instructor'], name='quickstart__instruc_f2f66a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='quickstart__status_f773af_idx'),
        ),
        migrations.DeleteModel(
            name='Schedules',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleconflict',
            unique_together={('schedule', 'conflicting_schedule')},
        ),
        migrations.AddIndex(
            model_name='schedulestudent',
            index=models.Index(fields=['schedule', 'student'], name='quickstart__schedul_72ea19_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulestudent',
            index=models.Index(fields=['status'], name='quickstart__status_42a7a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulestudent',
            unique_together={('schedule', 'student')},
        ),
    ]
