# Generated by Django 5.0.6 on 2024-07-15 07:02

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_classesmain_classcoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='classImage',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='class_images/'),
        ),
        migrations.AddField(
            model_name='classesmain',
            name='classVideo',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='class_videos/'),
        ),
    ]
