# Generated by Django 5.0.6 on 2025-02-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_booking_course_end_date_booking_course_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='_skip_recurring_creation',
            field=models.BooleanField(default=False),
        ),
    ]
