# Generated by Django 5.0.6 on 2025-02-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_booking__skip_recurring_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='_skip_recurring_creation',
        ),
    ]
