# Generated by Django 5.0.6 on 2024-07-17 06:09

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_classesmain_classimage_classesmain_classvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesmain',
            name='classImage',
        ),
        migrations.RemoveField(
            model_name='classesmain',
            name='classVideo',
        ),
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='class_images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quickstart.classesmain')),
            ],
            options={
                'db_table': 'classImages',
            },
        ),
    ]
