# Generated by Django 5.0.6 on 2024-11-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_remove_schedules_subclassid_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='quickstart.instructor'),
        ),
    ]
