# Generated by Django 5.0.6 on 2025-02-02 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_remove_booking__skip_recurring_creation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_booking_d33ada_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleinstance',
            name='schedule_in_date_9268fb_idx',
        ),
        migrations.RemoveField(
            model_name='scheduleinstance',
            name='capacity_reserved',
        ),
        migrations.AddField(
            model_name='booking',
            name='current_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleinstance',
            name='attendance_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course'), ('Recurring Classes', 'Recurring Classes')], default='Single Session', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddIndex(
            model_name='scheduleinstance',
            index=models.Index(fields=['date', 'time'], name='schedule_in_date_7db777_idx'),
        ),
    ]
