# Generated by Django 5.0.6 on 2024-11-12 07:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_booking_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name_plural': 'Business Information'},
        ),
        migrations.AlterModelOptions(
            name='classesmain',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='classesmain',
            name='additionalInfo',
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='owner',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classesmain',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='quickstart.instructor'),
        ),
        migrations.AddField(
            model_name='classesmain',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classesmain',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='quickstart.businessinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='businessDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='businessId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='quickstart.businessinfo'),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='classPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='classRating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='classTotalReviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
