# Generated by Django 5.0.6 on 2024-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_classesmain_classimage_classesmain_classvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='subclasses',
            name='subclassTags',
        ),
        migrations.AddField(
            model_name='subclasses',
            name='tags',
            field=models.ManyToManyField(related_name='subclasses', to='quickstart.tag'),
        ),
    ]
