# Generated by Django 5.0.6 on 2025-02-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_remove_booking_bookings_booking_d33ada_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='current_period_end',
        ),
    ]
