# Generated by Django 5.0.6 on 2025-02-03 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_remove_booking_current_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(blank=True, choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course'), ('Recurring Classes', 'Recurring Classes')], default='Single Session', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='quickstart.scheduleinstance'),
        ),
    ]
