# Generated by Django 5.0.6 on 2024-07-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_tag_remove_subclasses_subclasstags_subclasses_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclasses',
            name='tags',
        ),
        migrations.AddField(
            model_name='subclasses',
            name='subclassTags',
            field=models.CharField(default='Test Tag', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
