# Generated by Django 5.0.6 on 2025-02-03 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_alter_booking_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course'), ('Recurring Classes', 'Recurring Classes')], default='Single Session', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
