# Generated by Django 5.0.6 on 2024-07-30 03:20

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_remove_subclasses_tags_subclasses_subclasstags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesmain',
            name='classImage',
        ),
        migrations.RemoveField(
            model_name='classesmain',
            name='classVideo',
        ),
        migrations.AddField(
            model_name='subclasses',
            name='subclassImage',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='subclass_images/'),
        ),
    ]
