# Generated by Django 5.0.6 on 2025-02-03 03:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_alter_booking_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='quickstart.scheduleinstance'),
        ),
    ]
