# Generated by Django 5.0.6 on 2024-07-30 21:11

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_remove_classesmain_classimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='businessImage',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='business_images/'),
        ),
    ]
