# Generated by Django 5.0.6 on 2025-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_alter_booking_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoption',
            name='booking_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course'), ('Recurring Classes', 'Recurring Classes')], default='Single Session', max_length=20),
        ),
    ]
