# Generated by Django 5.0.6 on 2024-07-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_businessinfo_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='totalReviews',
            field=models.IntegerField(default=0),
        ),
    ]
