# Generated by Django 5.0.6 on 2025-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_alter_classoption_booking_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['option', 'is_active'], name='schedules_option__e82c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day', 'time'], name='schedules_day_dbac2a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleinstance',
            index=models.Index(fields=['schedule', 'status'], name='schedule_in_schedul_1c2d0b_idx'),
        ),
    ]
