# Generated by Django 5.0.6 on 2025-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_schedule_schedules_option__e82c9b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduleinstance',
            index=models.Index(fields=['schedule', 'date', 'status'], name='schedule_in_schedul_4fc78e_idx'),
        ),
    ]
