# Generated by Django 5.0.6 on 2025-02-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_scheduleinstance_schedule_in_schedul_4fc78e_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classesmain',
            index=models.Index(fields=['coordinates'], name='classes_coordin_a95392_idx'),
        ),
        migrations.AddIndex(
            model_name='classesmain',
            index=models.Index(fields=['location'], name='classes_locatio_d747df_idx'),
        ),
        migrations.AddIndex(
            model_name='classesmain',
            index=models.Index(fields=['businessId'], name='classes_busines_d15c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='classoption',
            index=models.Index(fields=['active', 'classId'], name='class_optio_active_5fd9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='classoption',
            index=models.Index(fields=['classId'], name='class_optio_classId_53639e_idx'),
        ),
    ]
