# Generated by Django 5.0.6 on 2025-02-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_booking_bookings_status_51373b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoption',
            name='auto_renew_default',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='sessions_per_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='allow_late_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='booking_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course')], default='Single Session', max_length=20),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='price_type',
            field=models.CharField(choices=[('per_session', 'Per Session'), ('full_course', 'Full Course')], default='per_session', max_length=20),
        ),
    ]
