# Generated by Django 5.0.6 on 2025-02-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_remove_classoption_auto_renew_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoption',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='total_sessions',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
