# Generated by Django 5.0.6 on 2025-02-12 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0024_remove_classoption_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedules_day_dbac2a_idx',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='maxParticipants',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='price',
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='maxParticipants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
