# Generated by Django 5.0.6 on 2025-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_remove_schedule_schedules_day_dbac2a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinstance',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
