# Generated by Django 5.0.6 on 2025-02-14 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0027_schedule_date_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_student_5b9171_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='course_end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sessions_per_week',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_sessions',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='enrollment_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course')], default='Single Session', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_user_id_1eeb34_idx'),
        ),
    ]
