# Generated by Django 5.0.6 on 2025-02-14 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0028_remove_booking_bookings_student_5b9171_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='schedule_instance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='education',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='business',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructornote',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructornote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentnote',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='class_option',
        ),
        migrations.AddField(
            model_name='studentnote',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='quickstart.businessinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentnote',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='business_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['user', 'business'], name='student_not_user_id_be9394_idx'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='InstructorNote',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
