# Generated by Django 5.0.6 on 2025-02-15 05:59

import django.core.validators
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0029_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='booking',
            field=models.OneToOneField(default=407, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='quickstart.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='classOption',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quickstart.classoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='businessId',
            field=models.ForeignKey(db_column='businessId', default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.businessinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='classId',
            field=models.ForeignKey(db_column='classId', on_delete=django.db.models.deletion.CASCADE, to='quickstart.classesmain'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['classId', 'classOption'], name='reviews_classId_038515_idx'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['booking'], name='reviews_booking_012755_idx'),
        ),
    ]
