# Generated by Django 5.0.6 on 2025-02-28 02:19

import django.db.models.deletion
import jsonfield.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quickstart', '0032_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'permission_groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default role for new users'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted'),
        ),
        migrations.CreateModel(
            name='EnhancedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('requires_mfa', models.BooleanField(default=False)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced', to='auth.permission')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='quickstart.permissiongroup')),
            ],
            options={
                'db_table': 'enhanced_permissions',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='quickstart.businessinfo')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('business_license', 'Business License'), ('id_verification', 'ID Verification'), ('certification', 'Professional Certification'), ('insurance', 'Insurance Documentation'), ('address_proof', 'Proof of Address'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='verification_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quickstart.verificationrequest')),
            ],
            options={
                'db_table': 'verification_documents',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('role_change', 'Role Changed'), ('permission_change', 'Permission Changed'), ('account_lock', 'Account Locked'), ('account_unlock', 'Account Unlocked'), ('password_reset', 'Password Reset'), ('failed_login', 'Failed Login'), ('verification_submit', 'Verification Submitted'), ('verification_approve', 'Verification Approved'), ('verification_reject', 'Verification Rejected'), ('system_setting_change', 'System Setting Changed'), ('data_export', 'Data Exported')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('metadata', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['target_user'], name='audit_logs_target__3f70c6_idx')],
            },
        ),
    ]
