# Generated by Django 5.0.6 on 2025-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0034_role_created_at_role_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(default='#64748b', help_text='HEX color code for this role', max_length=20),
        ),
    ]
