# Generated by Django 5.0.6 on 2025-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0035_role_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hierarchy_level',
            field=models.IntegerField(default=0, help_text='Higher number = higher privileges'),
        ),
    ]
