# Generated by Django 5.0.6 on 2025-02-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0036_role_hierarchy_level'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_email'], name='audit_logs_user_em_e4a257_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='audit_logs_user_id_d685f3_idx'),
        ),
    ]
