# Generated by Django 5.0.6 on 2025-03-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0037_auditlog_audit_logs_user_em_e4a257_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
