# Generated by Django 5.0.6 on 2025-03-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0038_classesmain_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classoption',
            name='class_optio_active_5fd9a5_idx',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='active',
        ),
    ]
