# Generated by Django 5.0.6 on 2025-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0039_remove_classoption_class_optio_active_5fd9a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='last_booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['featured'], name='business_in_feature_e8fcfc_idx'),
        ),
    ]
