# Generated by Django 5.0.6 on 2025-03-05 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0040_businessinfo_featured_businessinfo_last_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviews',
            name='reviews_classId_038515_idx',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='classOption',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='classId',
            field=models.ForeignKey(db_column='classId', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quickstart.classesmain'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['classId'], name='reviews_classId_765776_idx'),
        ),
    ]
