# Generated by Django 5.0.6 on 2025-03-05 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0041_remove_reviews_reviews_classid_038515_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='quickstart.booking'),
        ),
    ]
