# Generated by Django 5.0.6 on 2025-03-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0042_alter_reviews_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Class Categories',
                'db_table': 'class_categories',
            },
        ),
        migrations.AddField(
            model_name='reviews',
            name='business_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='report_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('hidden', 'Hidden')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='quickstart.classcategory'),
        ),
        migrations.CreateModel(
            name='ClassSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quickstart.classcategory')),
            ],
            options={
                'db_table': 'class_subcategories',
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='quickstart.classsubcategory'),
        ),
    ]
