# Generated by Django 5.0.6 on 2025-03-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0043_classcategory_reviews_business_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesmain',
            name='active',
        ),
        migrations.AddField(
            model_name='classesmain',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classesmain',
            index=models.Index(fields=['status'], name='classes_status_ae471a_idx'),
        ),
    ]
