# Generated by Django 5.0.6 on 2025-03-10 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0044_remove_classesmain_active_classesmain_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('hidden', 'Hidden')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('payment_method_type', models.CharField(default='card', max_length=20)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_message', models.TextField(blank=True)),
                ('billing_details', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='quickstart.booking')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_payment_intent_id'], name='payments_stripe__6cb0ea_idx'), models.Index(fields=['stripe_charge_id'], name='payments_stripe__3041dd_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
            },
        ),
    ]
