# Generated by Django 5.0.6 on 2025-03-11 02:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0045_alter_reviews_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='quickstart.booking'),
        ),
    ]
