# Generated by Django 5.0.6 on 2025-03-12 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0048_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quickstart.chatsession'),
        ),
    ]
