# Generated by Django 5.0.6 on 2025-03-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0049_alter_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('agent', 'Agent')], default='user', max_length=10),
        ),
    ]
