# Generated by Django 5.0.6 on 2025-03-24 22:31

import django.db.models.deletion
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0050_chatmessage_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=600),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('audience_type', models.CharField(choices=[('all_users', 'All Users'), ('segment', 'User Segment'), ('individual', 'Individual Users')], max_length=20)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('target_user_ids', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('template', 'Template')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='notification_attachments/')),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quickstart.notificationcampaign')),
            ],
            options={
                'db_table': 'notification_attachments',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='quickstart.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='UserSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict)),
                ('user_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_segments',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_9dff33_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['created_at'], name='notificatio_created_375143_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status'], name='notificatio_status_0adad2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_375460_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_7cfdee_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_3856f4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['created_at'], name='notificatio_created_a22fcf_idx'),
        ),
    ]
