# Generated by Django 5.0.6 on 2025-03-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0051_alter_supportticket_subject_notificationcampaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='template',
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
