# Generated by Django 5.0.6 on 2025-04-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0052_remove_notificationcampaign_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_role', 'Can change the role assigned to any user'), ('lock_user', 'Can lock/unlock any user account'), ('reset_user_password', 'Can initiate password reset for any user'), ('view_user_metrics', 'Can view user management metrics'), ('access_user_admin', 'Can access the user administration section')]},
        ),
    ]
