# Generated by Django 5.0.6 on 2025-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0053_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'permissions': [('toggle_business_feature', 'Can toggle the featured status for any business'), ('view_business_metrics', 'Can view aggregated business management statistics'), ('export_business_data', 'Can export business data as CSV'), ('send_business_announcements', 'Can send platform announcements to businesses'), ('access_business_admin', 'Can access the Business Administration section')], 'verbose_name_plural': 'Business Information'},
        ),
    ]
