# Generated by Django 5.0.6 on 2025-04-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0054_alter_businessinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcategory',
            options={'permissions': [('view_category_stats', 'Can view category statistics'), ('access_category_admin', 'Can access the Category Administration section')], 'verbose_name_plural': 'Class Categories'},
        ),
        migrations.AlterModelOptions(
            name='classesmain',
            options={'permissions': [('change_class_status', 'Can change the status (active/inactive/suspended) of any class'), ('view_class_analytics', 'Can view aggregated class analytics'), ('export_class_data', 'Can export class data'), ('access_class_admin', 'Can access the Class Administration section')]},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('access_review_admin', 'Can access the Review Moderation section')]},
        ),
    ]
