# Generated by Django 5.0.6 on 2025-04-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0055_alter_classcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('cancel_own_booking', 'Can cancel their own booking'), ('mark_booking_attendance', 'Can mark attendance for this booking'), ('cancel_any_booking', "Can cancel any user's booking (Admin)"), ('view_booking_analytics', 'Can view aggregated booking analytics'), ('export_booking_data', 'Can export booking data'), ('access_booking_admin', 'Can access the Booking Administration section')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'permissions': [('process_refund', 'Can process refunds for any payment'), ('mark_payment_paid', 'Can manually mark a payment as paid'), ('view_payment_stats', 'Can view aggregated payment statistics'), ('export_payment_data', 'Can export payment data'), ('access_payment_admin', 'Can access the Payment Administration section')]},
        ),
    ]
