# Generated by Django 5.0.6 on 2025-04-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0056_alter_booking_options_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'permissions': [('toggle_business_feature', 'Can toggle the featured status for any business'), ('view_business_metrics', 'Can view aggregated business management statistics'), ('export_business_data', 'Can export business data as CSV'), ('send_business_announcements', 'Can send platform announcements to businesses'), ('access_business_admin', 'Can access the Business Administration section'), ('manage_own_classes', 'Can create/edit classes, options, schedules for own business'), ('manage_own_schedule_instances', 'Can manage instances (attendance, cancel) for own classes'), ('view_own_business_bookings', 'Can view bookings for own business'), ('manage_own_business_profile', 'Can edit own business profile details'), ('manage_business_staff', 'Can manage staff (instructors, managers) for own business')], 'verbose_name_plural': 'Business Information'},
        ),
    ]
