# Generated by Django 5.0.6 on 2025-04-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0057_alter_businessinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationcampaign',
            options={'ordering': ['-created_at'], 'permissions': [('send_notification_campaign', 'Can send notification campaigns'), ('cancel_notification_campaign', 'Can cancel scheduled campaigns'), ('duplicate_notification_campaign', 'Can duplicate campaigns'), ('view_notification_metrics', 'Can view notification campaign metrics'), ('access_notification_admin', 'Can access Notification Management section')]},
        ),
        migrations.AlterModelOptions(
            name='usersegment',
            options={'ordering': ['name'], 'permissions': [('view_segment_users', 'Can view users within a segment'), ('refresh_segment_counts', 'Can trigger recalculation of segment counts'), ('access_segment_admin', 'Can access User Segment Management section')]},
        ),
    ]
