# Generated by Django 5.0.6 on 2025-04-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0058_alter_notificationcampaign_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'permissions': [('reply_any_support_ticket', 'Can reply to any support ticket (Admin/Agent)'), ('assign_support_ticket', 'Can assign any support ticket to an agent'), ('resolve_support_ticket', 'Can resolve/close any support ticket'), ('view_support_ticket_stats', 'Can view aggregated support ticket statistics'), ('export_support_ticket_data', 'Can export support ticket data'), ('access_support_admin', 'Can access Support Ticket Administration'), ('reply_own_support_ticket', 'Can reply to own support tickets')]},
        ),
    ]
