# Generated by Django 5.0.6 on 2025-04-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0059_alter_supportticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_role', 'Can change the role assigned to any user'), ('lock_user', 'Can lock/unlock any user account'), ('reset_user_password', 'Can initiate password reset for any user'), ('view_user_metrics', 'Can view user management metrics'), ('access_user_admin', 'Can access the user administration section'), ('view_system_metrics', 'Can view real-time system performance metrics')]},
        ),
    ]
