# Generated by Django 5.0.6 on 2025-04-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0061_alter_businessinfo_options_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('cancel_any_booking', "Can cancel any user's booking (Admin)"), ('view_booking_analytics', 'Can view aggregated booking analytics'), ('export_booking_data', 'Can export booking data'), ('access_booking_admin', 'Can access the Booking Administration section'), ('mark_booking_attendance', 'Can mark attendance for bookings in own business')]},
        ),
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'permissions': [('toggle_business_feature', 'Can toggle the featured status for any business'), ('view_business_metrics', 'Can view aggregated business management statistics'), ('export_business_data', 'Can export business data as CSV'), ('send_business_announcements', 'Can send platform announcements to businesses'), ('access_business_admin', 'Can access the Business Administration section'), ('manage_own_classes', 'Can create/edit classes, options, schedules for own business'), ('manage_own_schedule_instances', 'Can manage instances (attendance, cancel) for own classes'), ('view_own_business_bookings', 'Can view bookings for own business'), ('manage_own_business_profile', 'Can edit own business profile details'), ('manage_business_staff', 'Can manage staff (instructors, managers) for own business'), ('access_business_dashboard', 'Can access the dashboard for managing their own business'), ('view_business_revenue_analytics', 'Can view revenue analytics for own business'), ('export_business_revenue_data', 'Can export revenue data for own business'), ('view_business_students', 'Can view students associated with own business'), ('add_studentnote', 'Can add notes to students associated with own business'), ('view_studentnote', 'Can view notes for students associated with own business')], 'verbose_name_plural': 'Business Information'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_role', 'Can change the role assigned to any user'), ('lock_user', 'Can lock/unlock any user account'), ('reset_user_password', 'Can initiate password reset for any user'), ('view_user_metrics', 'Can view user management metrics'), ('access_user_admin', 'Can access the user administration section'), ('view_system_metrics', 'Can view real-time system performance metrics'), ('access_admin_dashboard', 'Can access the main platform administration dashboard'), ('reply_own_support_ticket', 'Can reply to own support tickets'), ('cancel_own_booking', 'Can cancel their own booking'), ('add_supportticket', 'Can create new support tickets')]},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'permissions': [('reply_any_support_ticket', 'Can reply to any support ticket (Admin/Agent)'), ('assign_support_ticket', 'Can assign any support ticket to an agent'), ('resolve_support_ticket', 'Can resolve/close any support ticket'), ('view_support_ticket_stats', 'Can view aggregated support ticket statistics'), ('export_support_ticket_data', 'Can export support ticket data'), ('access_support_admin', 'Can access Support Ticket Administration')]},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('agent', 'Agent'), ('system', 'System')], default='user', max_length=10),
        ),
    ]
