# Generated by Django 5.0.6 on 2025-04-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0062_alter_booking_options_alter_businessinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('cancel_any_booking', "Can cancel any user's booking (Admin)"), ('view_booking_analytics', 'Can view aggregated booking analytics'), ('export_booking_data', 'Can export booking data'), ('access_booking_admin', 'Can access the Booking Administration section'), ('mark_booking_attendance', 'Can mark attendance for bookings in own business'), ('view_own_booking_analytics', 'Can view booking analytics for own business'), ('cancel_business_booking', 'Can cancel bookings within own business')]},
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='adminContactEmail',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='adminContactPhone',
        ),
    ]
