# Generated by Django 5.0.6 on 2025-04-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0063_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classimage',
            name='isCover',
            field=models.BooleanField(default=False),
        ),
    ]
