# Generated by Django 5.0.6 on 2025-04-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0064_classimage_iscover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('access_review_admin', 'Can access the Review Moderation section'), ('view_own_business_reviews', 'Can view reviews related to own business'), ('add_business_review_response', 'Can add/edit responses to reviews on own classes')]},
        ),
    ]
