# Generated by Django 5.0.6 on 2025-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0065_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='totalReviews',
        ),
        migrations.AddField(
            model_name='classesmain',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
