# Generated by Django 5.0.6 on 2025-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0066_remove_businessinfo_totalreviews_classesmain_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesmain',
            name='website',
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
