# Generated by Django 5.0.6 on 2025-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0067_remove_classesmain_website_businessinfo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='cancellationNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='newBookingNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='refundPolicy',
            field=models.CharField(choices=[('full', 'Full refund if cancelled within policy'), ('partial', 'Partial refund (details TBD/in description)'), ('credit', 'Account credit only'), ('none', 'No refunds')], default='partial', max_length=20),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='reminderNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='smsNotifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='stripe_account_status',
            field=models.CharField(blank=True, choices=[('unlinked', 'Unlinked'), ('pending', 'Pending Verification'), ('active', 'Connected & Active'), ('restricted', 'Account Restricted'), ('incomplete', 'Incomplete Setup')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='ageGroups',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='cancellationPolicy',
            field=models.CharField(choices=[('flexible', 'Flexible (e.g., 24 hours notice)'), ('moderate', 'Moderate (e.g., 48 hours notice)'), ('strict', 'Strict (e.g., 72 hours notice)'), ('non_refundable', 'Non-refundable')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='classFormats',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='showExactLocation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='skillLevels',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='subcategories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['verificationStatus'], name='business_in_verific_079387_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['stripe_account_id'], name='business_in_stripe__36de85_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['stripe_account_status'], name='business_in_stripe__90d9be_idx'),
        ),
    ]
