# Generated by Django 5.0.6 on 2025-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0068_businessinfo_cancellationnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='ageGroups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='classFormats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='skillLevels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='subcategories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
