# Generated by Django 5.0.6 on 2025-04-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0069_alter_businessinfo_agegroups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='cancellationPolicy',
        ),
    ]
