# Generated by Django 5.0.6 on 2025-04-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0070_remove_businessinfo_cancellationpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
