# Generated by Django 5.0.6 on 2025-04-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0071_alter_businessinfo_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'ordering': ['-submitted_at'], 'permissions': [('view_all_verificationrequests', 'Can view all verification requests'), ('process_verificationrequest', 'Can approve or reject verification requests')]},
        ),
    ]
