# Generated by Django 5.0.6 on 2025-04-27 07:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0072_alter_verificationrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, help_text='Cached average rating from approved reviews for this business', max_digits=3),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='total_reviews_count',
            field=models.IntegerField(default=0, editable=False, help_text='Cached count of approved reviews for this business'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='verificationStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['total_reviews_count'], name='business_in_total_r_c1e332_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['average_rating'], name='business_in_average_a941ab_idx'),
        ),
    ]
