# Generated by Django 5.0.6 on 2025-05-17 00:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0073_businessinfo_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='classesmain',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='classes_search__e4427d_gin'),
        ),
    ]
