# Generated by Django 5.0.6 on 2025-05-17 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0074_classesmain_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classesmain',
            options={'permissions': [('change_class_status', 'Can change class status'), ('view_class_analytics', 'View class analytics'), ('export_class_data', 'Can export class data'), ('access_class_admin', 'Access Class Admin')]},
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='businessId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to='quickstart.businessinfo'),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_in_category', to='quickstart.classcategory'),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_in_subcategory', to='quickstart.classsubcategory'),
        ),
    ]
