# Generated by Django 5.0.6 on 2025-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0075_alter_classesmain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
