# Generated by Django 5.0.6 on 2025-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0076_alter_verificationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participant_details',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts for participant names, e.g., [{'name': 'Jane Doe'}, {'name': 'John Smith'}]"),
        ),
    ]
