# Generated by Django 5.0.6 on 2025-05-28 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quickstart', '0078_businessinfo_business_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_booking', 'New Booking'), ('booking_cancelled_by_user', 'Booking Cancelled by User'), ('booking_cancelled_by_biz', 'Booking Cancelled by Business'), ('class_reminder_biz', 'Class Reminder for Business'), ('class_reminder_student', 'Class Reminder for Student'), ('new_review', 'New Review'), ('review_response', 'Review Response from Business'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('payout_initiated', 'Payout Initiated'), ('stripe_action_required', 'Stripe Action Required'), ('profile_incomplete', 'Profile Incomplete'), ('system_announcement', 'System Announcement'), ('new_message_support', 'New Message in Support Ticket')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, help_text="e.g., Lucide icon name like 'UserPlus'", max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text="e.g., '#3b82f6'", max_length=20, null=True)),
                ('link_web', models.CharField(blank=True, help_text='Relative URL for web client', max_length=255, null=True)),
                ('business', models.ForeignKey(blank=True, help_text='Business context for this notification, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_notifications', to='quickstart.businessinfo')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ScheduleBreak',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'is_read', '-created_at'], name='notificatio_busines_dac1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
    ]
