# Generated by Django 5.0.6 on 2025-05-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0079_notification_delete_schedulebreak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='businessId',
            field=models.ForeignKey(db_column='businessId', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_directly_to_business', to='quickstart.businessinfo'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='business_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='report_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['status'], name='reviews_status_12ddaa_idx'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['reported'], name='reviews_reporte_518b07_idx'),
        ),
    ]
