# Generated by Django 5.0.6 on 2025-05-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0080_reviews_reported_at_reviews_responded_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedules_option__e82c9b_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_active',
        ),
    ]
