# Generated by Django 5.0.6 on 2025-05-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0081_remove_schedule_schedules_option__e82c9b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_facing_reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user_facing_reference'], name='bookings_user_fa_55ad8a_idx'),
        ),
    ]
