# Generated by Django 5.0.6 on 2025-06-04 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0083_remove_businessinfo_refundpolicy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='classoption',
            name='title',
        ),
        migrations.AddField(
            model_name='classoption',
            name='cancellationRefundPercentage',
            field=models.PositiveIntegerField(default=100, help_text='Percentage of refund if cancellation policy conditions are met (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='booking_type',
            field=models.CharField(choices=[('Single Session', 'Single Session')], default='Single Session', max_length=20),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='cancellationPolicy',
            field=models.CharField(choices=[('flexible', 'Flexible (up to 1 hour before)'), ('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('strict', 'Strict (Non-refundable)')], default='flexible', max_length=30),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
