# Generated by Django 5.0.6 on 2025-06-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0084_remove_classoption_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoption',
            name='image',
        ),
    ]
