# Generated by Django 5.0.6 on 2025-06-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0085_remove_classoption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='contact_privacy',
            field=models.CharField(choices=[('on_booking', 'Show After Booking'), ('public', 'Show Publicly'), ('public_with_chat', 'Show Publicly & Allow Chat')], default='on_booking', help_text='Choose who can see your direct contact information.', max_length=20),
        ),
    ]
