# Generated by Django 5.0.6 on 2025-06-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0086_businessinfo_contact_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('cancel_any_booking', "Can cancel any user's booking (Admin)"), ('view_booking_analytics', 'Can view aggregated booking analytics'), ('export_booking_data', 'Can export booking data'), ('access_booking_admin', 'Can access the Booking Administration section'), ('view_own_booking_analytics', 'Can view booking analytics for own business'), ('cancel_business_booking', 'Can cancel bookings within own business')]},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='attendance_marked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='scheduleinstance',
            name='attendance_marked',
        ),
        migrations.RemoveField(
            model_name='scheduleinstance',
            name='instructor_notes',
        ),
    ]
