# Generated by Django 5.0.6 on 2025-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0087_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('role_change', 'Role Changed'), ('permission_change', 'Permission Changed'), ('account_lock', 'Account Locked'), ('account_unlock', 'Account Unlocked'), ('password_reset', 'Password Reset'), ('failed_login', 'Failed Login'), ('verification_submit', 'Verification Submitted'), ('verification_approve', 'Verification Approved'), ('verification_reject', 'Verification Rejected'), ('system_setting_change', 'System Setting Changed'), ('data_export', 'Data Exported'), ('business_update', 'Business Updated'), ('business_delete', 'Business Deleted'), ('business_delete_failed', 'Business Delete Failed'), ('business_activate', 'Business Activated'), ('business_deactivate', 'Business Deactivated'), ('business_feature', 'Business Featured'), ('business_unfeature', 'Business Unfeatured')], max_length=30),
        ),
    ]
