# Generated by Django 5.0.6 on 2025-06-11 19:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0088_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_unsubscribed',
            field=models.BooleanField(default=False, help_text='User has opted out of marketing emails.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of the master Celery task for sending this campaign.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='click_count',
            field=models.IntegerField(default=0, help_text='Count of unique clicks.'),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The portion of the payment amount that is the platform's service fee.", max_digits=10),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['celery_task_id'], name='notificatio_celery__105822_idx'),
        ),
    ]
