# Generated by Django 5.0.6 on 2025-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0089_customuser_is_unsubscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the first agent reply.', null=True),
        ),
    ]
