# Generated by Django 5.0.6 on 2025-06-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0090_supportticket_first_responded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorited',
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['userId', '-createdAt'], name='favorites_userId__659d6c_idx'),
        ),
    ]
