# Generated by Django 5.0.6 on 2025-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0091_remove_customuser_favorited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='quickstart.Favorites', to='quickstart.classesmain'),
        ),
    ]
