# Generated by Django 5.0.6 on 2025-06-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0092_customuser_favorited'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessinfo',
            name='business_in_classCa_d3ac0a_idx',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='classCategory',
        ),
    ]
