# Generated by Django 5.0.6 on 2025-06-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0093_remove_businessinfo_business_in_classca_d3ac0a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='classCategory',
            field=models.ForeignKey(help_text='The primary category that defines the business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses_in_category', to='quickstart.classcategory'),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['classCategory'], name='business_in_classCa_b6cbe2_idx'),
        ),
    ]
