# Generated by Django 5.0.6 on 2025-06-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0094_businessinfo_classcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, help_text="An optional name for this schedule, e.g., 'Weekend Morning Session'.", max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['name'], name='schedules_name_ec822e_idx'),
        ),
    ]
