# Generated by Django 5.0.6 on 2025-06-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0095_schedule_name_schedule_schedules_name_ec822e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcategory',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Name of the Lucide React icon (e.g., 'Music', 'Palette'). See lucide.dev for names.", max_length=50, null=True),
        ),
    ]
