# Generated by Django 5.0.6 on 2025-06-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0096_classcategory_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmain',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_in_category', to='quickstart.classcategory'),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_in_subcategory', to='quickstart.classsubcategory'),
        ),
    ]
