# Generated by Django 5.0.6 on 2025-06-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0097_alter_classesmain_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmain',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_in_subcategory', to='quickstart.classsubcategory'),
        ),
    ]
