# Generated by Django 5.0.6 on 2025-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0098_alter_classesmain_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='businessImage',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='verificationDocument',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='classimage',
            name='image',
            field=models.ImageField(upload_to='class_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='notificationattachment',
            name='file',
            field=models.FileField(upload_to='notification_attachments/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
