# Generated by Django 5.0.6 on 2025-07-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0099_alter_businessinfo_businessimage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessinfo',
            name='business_in_classCa_b6cbe2_idx',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='classCategory',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='subcategories',
        ),
    ]
