# Generated by Django 5.0.6 on 2025-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0100_remove_businessinfo_business_in_classca_b6cbe2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcategory',
            name='key',
        ),
        migrations.AddField(
            model_name='classcategory',
            name='description',
            field=models.TextField(blank=True, help_text='A short, catchy description for the homepage card.'),
        ),
        migrations.AddField(
            model_name='classcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image displayed on the homepage category card.', null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='classcategory',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this category on the homepage.'),
        ),
        migrations.AddField(
            model_name='classcategory',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier based on the name.', max_length=120, null=True, unique=True),
        ),
    ]
