# Generated by Django 5.0.6 on 2025-07-13 05:07

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """
    Populates the slug for any existing ClassCategory that doesn't have one.
    Ensures uniqueness by appending a counter if a slug already exists.
    """
    ClassCategory = apps.get_model("quickstart", "ClassCategory")
    for category in ClassCategory.objects.all():
        # Only process categories where the slug is currently empty
        if not category.slug:
            # Generate the initial slug from the category name
            slug = slugify(category.name)

            # Ensure the generated slug is unique
            unique_slug = slug
            counter = 1
            # Keep checking for existence and append a counter until a unique slug is found
            while ClassCategory.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{slug}-{counter}"
                counter += 1

            category.slug = unique_slug
            category.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "quickstart",
            "0101_remove_classcategory_key_classcategory_description_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
