# Generated by Django 5.0.6 on 2025-07-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0102_populate_category_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcategory',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier based on the name.', max_length=120, unique=True),
        ),
    ]
