# Generated by Django 5.0.6 on 2025-07-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0103_alter_classcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcategory',
            name='slug',
        ),
    ]
