# Generated by Django 5.0.6 on 2025-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0104_remove_classcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcategory',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier based on the name.', max_length=120, null=True, unique=True),
        ),
    ]
