# Generated by Django 5.0.6 on 2025-07-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0106_populate_category_slugs_again"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classcategory",
            old_name="slug",
            new_name="key",
        ),
    ]
