# Generated by Django 5.0.6 on 2025-07-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0107_rename_category_slug_to_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcategory',
            name='key',
            field=models.SlugField(help_text='URL-friendly identifier. Auto-generates from name if not provided.', max_length=120, unique=True),
        ),
    ]
