# Generated by Django 5.0.6 on 2025-07-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0108_alter_classcategory_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classimage',
            name='image',
            field=models.ImageField(upload_to='originals/class_images/'),
        ),
    ]
