# Generated by Django 5.0.6 on 2025-07-15 01:20

import quickstart.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0110_alter_businessinfo_businessimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='businessImage',
            field=models.ImageField(blank=True, null=True, storage=quickstart.custom_storages.WebPStorage(), upload_to='originals/business_images/'),
        ),
        migrations.AlterField(
            model_name='classcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image displayed on the homepage category card.', null=True, storage=quickstart.custom_storages.WebPStorage(), upload_to='originals/category_images/'),
        ),
        migrations.AlterField(
            model_name='classimage',
            name='image',
            field=models.ImageField(storage=quickstart.custom_storages.WebPStorage(), upload_to='originals/class_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=quickstart.custom_storages.WebPStorage(), upload_to='originals/avatars/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=quickstart.custom_storages.WebPStorage(), upload_to='originals/review_images/'),
        ),
    ]
