# Generated by Django 5.0.6 on 2025-07-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0111_alter_businessinfo_businessimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='classesmain',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
