# Generated by Django 5.0.6 on 2025-07-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0115_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='businessImage',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='originals/business_images/'),
        ),
    ]
