# Generated by Django 5.0.6 on 2025-07-21 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0116_alter_businessinfo_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Flexible (up to 1 hour before)'), ('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('strict', 'Strict (Non-refundable)')], default='flexible', help_text='The cancellation policy snapshotted at the time of booking.', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_refund_percentage',
            field=models.PositiveIntegerField(default=100, help_text='The refund percentage snapshotted at the time of booking.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
