# Generated by Django 5.0.6 on 2025-07-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0117_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classimage',
            name='image',
            field=models.ImageField(help_text='Image uploaded by the user, e.g., a photo from the class.', max_length=255, upload_to='originals/class_images/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, help_text='Image uploaded by the user, e.g., a photo from the class.', max_length=255, null=True, upload_to='originals/review_images/'),
        ),
    ]
