# Generated by Django 5.0.6 on 2025-07-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0118_alter_classimage_image_alter_reviews_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'permissions': [('reply_any_support_ticket', 'Can reply to any support ticket (Admin/Agent)'), ('assign_support_ticket', 'Can assign any support ticket to an agent'), ('change_ticket_status', 'Can change ticket status (e.g., resolve, close)'), ('view_assignable_agents', 'Can view the list of assignable support agents'), ('view_support_ticket_stats', 'Can view aggregated support ticket statistics'), ('export_support_ticket_data', 'Can export support ticket data'), ('access_support_admin', 'Can access Support Ticket Administration')]},
        ),
    ]
