# Generated by Django 5.0.6 on 2025-07-23 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0119_alter_supportticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='chat_session',
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-updated_at'], 'permissions': [('access_support_admin', 'Can access Support Ticket Administration'), ('assign_support_ticket', 'Can assign any support ticket to an agent'), ('view_support_ticket_stats', 'Can view support ticket statistics'), ('export_support_ticket_data', 'Can export support ticket data'), ('view_assignable_agents', 'Can view list of assignable support agents')]},
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='first_responded_at',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_agent_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_agent_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_user_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_facing_id',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Admin', 'Super Admin', 'Support Agent']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(help_text='Initial description of the issue.'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TicketHistoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(help_text="Snapshot of the user's email", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(help_text='Description of the event', max_length=512)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='quickstart.supportticket')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (can be system)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ticket_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='quickstart.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
