# Generated by Django 5.0.6 on 2025-07-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0120_remove_chatsession_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug. Auto-generated from title and city.', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='classesmain',
            index=models.Index(fields=['slug'], name='classes_slug_a29860_idx'),
        ),
    ]
