# Generated by Django 5.0.6 on 2025-07-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0122_populate_class_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmain',
            name='slug',
            field=models.SlugField(help_text='SEO-friendly URL slug. Auto-generated from title and city.', max_length=255, unique=True),
        ),
    ]
