# Generated by Django 5.0.6 on 2025-07-25 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0123_alter_classesmain_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_transfer_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount transferred to the business in the specified currency.', max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(help_text='Status of the transfer from Stripe (e.g., pending, paid, failed).', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], db_index=True, default='pending', help_text='Tracks the payout status for this specific booking.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payout_status'], name='bookings_payout__0dbdf9_idx'),
        ),
        migrations.AddField(
            model_name='payout',
            name='bookings',
            field=models.ManyToManyField(related_name='payouts', to='quickstart.booking'),
        ),
        migrations.AddField(
            model_name='payout',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='quickstart.businessinfo'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['business'], name='payouts_busines_588ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payouts_status_20cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['arrival_date'], name='payouts_arrival_ac3746_idx'),
        ),
    ]
