# Generated by Django 5.0.6 on 2025-07-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0124_payout_booking_payout_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='currency',
            field=models.CharField(default='CAD', help_text='3-letter ISO currency code, e.g., CAD, USD.', max_length=3),
        ),
    ]
