# Generated by Django 5.0.6 on 2025-07-26 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0125_businessinfo_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'blog_categories',
                'ordering': ['name'],
                'permissions': [('manage_blog_categories', 'Can create, edit, and delete blog categories')],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_role', 'Can change the role assigned to any user'), ('lock_user', 'Can lock/unlock any user account'), ('reset_user_password', 'Can initiate password reset for any user'), ('view_user_metrics', 'Can view user management metrics'), ('access_user_admin', 'Can access the user administration section'), ('view_system_metrics', 'Can view real-time system performance metrics'), ('access_admin_dashboard', 'Can access the main platform administration dashboard'), ('access_blog_admin', 'Can access the Blog Management section'), ('reply_own_support_ticket', 'Can reply to own support tickets'), ('cancel_own_booking', 'Can cancel their own booking'), ('add_supportticket', 'Can create new support tickets')]},
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='A short summary of the post.', max_length=500)),
                ('content', models.TextField(help_text='The full content of the blog post in HTML format.')),
                ('image_url', models.URLField(help_text='URL for the main post image.', max_length=1024)),
                ('tags', models.JSONField(blank=True, default=list, help_text="A list of tags, e.g., ['Community', 'Education']")),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='draft', max_length=10)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the post is published.')),
                ('read_time', models.PositiveIntegerField(default=0, help_text='Estimated read time in minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='quickstart.blogcategory')),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_date'],
                'permissions': [('manage_blog_posts', 'Can create, edit, and delete blog posts')],
            },
        ),
    ]
