# Generated by Django 5.0.6 on 2025-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0126_blogcategory_alter_customuser_options_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at'], 'permissions': [('access_payout_admin', 'Can access the Payout Administration section'), ('view_payout_analytics', 'Can view aggregated payout analytics'), ('export_payout_data', 'Can export payout data'), ('trigger_manual_payout', 'Can trigger a manual payout process'), ('retry_failed_payout', 'Can retry a failed payout transfer')]},
        ),
        migrations.RemoveField(
            model_name='payout',
            name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='payouts',
            field=models.ManyToManyField(related_name='bookings', to='quickstart.payout'),
        ),
    ]
