# Generated by Django 5.0.6 on 2025-07-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0127_alter_payout_options_remove_payout_bookings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
