# Generated by Django 5.0.6 on 2025-08-02 06:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0129_remove_classesmain_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csuid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('boundary_type', models.CharField(default='Census Subdivision', max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Geographic Boundaries',
            },
        ),
        migrations.RenameIndex(
            model_name='classesmain',
            new_name='classes_point_0412ee_gist',
            old_name='classes_point_gist_idx',
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Represents the geographic location (longitude, latitude).', null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='geographicboundary',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='quickstart__geom_60af96_gist'),
        ),
    ]
