# Generated by Django 5.0.6 on 2025-08-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0130_geographicboundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='quickstart.scheduleinstance'),
        ),
    ]
