# Generated by Django 5.0.6 on 2025-08-07 06:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0131_alter_booking_schedule_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal name for this discount/coupon.', max_length=150)),
                ('code', models.CharField(blank=True, db_index=True, help_text='The code customers enter to get the discount. Leave blank for automatic discounts.', max_length=50, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='The value of the discount (e.g., 20.00 for 20% or 10.00 for $10).', max_digits=10)),
                ('scope', models.CharField(choices=[('class', 'Entire Class'), ('schedule_group', 'Specific Schedule Group')], default='class', help_text='What this discount applies to.', max_length=20)),
                ('target_schedule_group_name', models.CharField(blank=True, help_text="Matches the 'name' field on a Schedule. Required if scope is 'Specific Schedule Group'.", max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Leave blank for no expiration date.', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max number of times this can be used in total.', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, default=1, help_text='How many times a single user can use this. Leave blank for unlimited.', null=True)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The minimum booking total required to use this discount.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='quickstart.businessinfo')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='quickstart.classesmain')),
                ('target_class_option', models.ForeignKey(blank=True, help_text="The class option for the schedule group. Required if scope is 'Specific Schedule Group'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='quickstart.classoption')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.booking')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quickstart.discount')),
            ],
            options={
                'db_table': 'applied_discounts',
                'unique_together': {('booking', 'discount')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discounts',
            field=models.ManyToManyField(related_name='bookings', through='quickstart.AppliedDiscount', to='quickstart.discount'),
        ),
    ]
