# Generated by Django 5.0.6 on 2025-08-17 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quickstart', '0132_discount_applieddiscount_booking_discounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'permissions': [('toggle_business_feature', 'Can toggle the featured status for any business'), ('manage_business_staff', 'Can invite, remove, and manage staff for own business'), ('view_business_metrics', 'Can view aggregated business management statistics'), ('export_business_data', 'Can export business data as CSV'), ('send_business_announcements', 'Can send platform announcements to businesses'), ('access_business_admin', 'Can access the Business Administration section'), ('manage_own_classes', 'Can create/edit classes, options, schedules for own business'), ('manage_own_schedule_instances', 'Can manage instances (attendance, cancel) for own classes'), ('view_own_business_bookings', 'Can view bookings for own business'), ('manage_own_business_profile', 'Can edit own business profile details'), ('access_business_dashboard', 'Can access the dashboard for managing their own business'), ('view_business_revenue_analytics', 'Can view revenue analytics for own business'), ('export_business_revenue_data', 'Can export revenue data for own business'), ('view_business_students', 'Can view students associated with own business'), ('add_studentnote', 'Can add notes to students associated with own business'), ('view_studentnote', 'Can view notes for students associated with own business')], 'verbose_name_plural': 'Business Information'},
        ),
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='quickstart.businessinfo')),
                ('permissions', models.ManyToManyField(blank=True, limit_choices_to={'codename__in': ['manage_own_classes', 'manage_own_schedule_instances', 'view_own_business_bookings', 'manage_own_business_profile', 'manage_business_staff', 'view_business_revenue_analytics', 'export_business_revenue_data', 'view_business_students', 'add_studentnote', 'view_studentnote', 'view_own_booking_analytics', 'cancel_business_booking', 'view_own_business_reviews', 'add_business_review_response', 'manage_own_business_discounts'], 'content_type__app_label': 'quickstart'}, to='auth.permission')),
            ],
            options={
                'db_table': 'business_roles',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BusinessStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('invited_email', models.EmailField(db_index=True, max_length=254)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='quickstart.businessinfo')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quickstart.businessrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_staff',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'invited_email'), ('business', 'user')},
            },
        ),
    ]
