# Generated by Django 5.0.6 on 2025-08-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0133_alter_businessinfo_options_businessrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='ui_category',
            field=models.CharField(blank=True, db_index=True, help_text="A category key for specific UIs, e.g., 'business_role_editor'.", max_length=50, null=True),
        ),
    ]
