# Generated by Django 5.0.6 on 2025-08-18 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0134_permissiongroup_ui_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
