# Generated by Django 5.0.6 on 2025-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quickstart', '0135_alter_businessstaff_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__in': ['manage_own_classes', 'manage_own_schedule_instances', 'view_own_business_bookings', 'manage_own_business_profile', 'manage_business_staff', 'manage_business_roles', 'view_business_revenue_analytics', 'export_business_revenue_data', 'view_business_students', 'add_studentnote', 'view_studentnote', 'view_own_booking_analytics', 'cancel_business_booking', 'view_own_business_reviews', 'add_business_review_response', 'manage_own_business_discounts', 'access_business_dashboard'], 'content_type__app_label': 'quickstart'}, to='auth.permission'),
        ),
    ]
