# Generated by Django 5.0.6 on 2025-08-21 04:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0137_alter_businessinfo_options_alter_studentnote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The public name of the tier (e.g., 'Founding Partner', 'Premium Partner').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of who this tier is for.')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='The platform fee percentage for this tier (e.g., enter 10 for 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_default', models.BooleanField(default=False, help_text='Set this to True for the standard, default tier that new businesses are assigned to. Only one tier should be the default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partner_tiers',
                'ordering': ['fee_percentage', 'name'],
            },
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='partner_tier',
            field=models.ForeignKey(blank=True, help_text='The partnership tier for this business, which determines their platform fee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='quickstart.partnertier'),
        ),
    ]
