# Generated by Django 5.0.6 on 2025-08-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0138_partnertier_businessinfo_partner_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.businessrole'),
        ),
    ]
