# Generated by Django 5.0.6 on 2025-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0140_remove_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='businessHours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='businessUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='preferredContact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text Message'), ('both', 'Both Email and Phone')], max_length=20),
        ),
    ]
