# Generated by Django 5.0.6 on 2025-08-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0142_migrate_business_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='closingTime',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='openingTime',
        ),
    ]
