# Generated by Django 5.0.6 on 2025-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0143_remove_businessinfo_closingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
