# Generated by Django 5.0.6 on 2025-08-29 04:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0144_classesmain_unit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service_fee_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='net_payout_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The final net amount to be transferred to the business (their revenue + their share of tax).', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The portion of the payment (pre-tax) that is the platform's service fee.", max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The portion of the tax amount that corresponds to the platform fee.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The total HST/tax amount included in the 'amount'.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The grand total amount charged to the customer, including tax.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
    ]
