# Generated by Django 5.0.6 on 2025-09-01 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0145_remove_payment_service_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='manual_entry', help_text="e.g., 'imported_csv', 'manual_entry', 'website_form'", max_length=50)),
                ('status', models.CharField(default='active', help_text="e.g., 'lead', 'active', 'inactive'", max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for segmentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='quickstart.businessinfo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contacts',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('business', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(help_text="e.g., 'Room', 'Equipment'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'crm_resources',
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='quickstart.businessinfo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(related_name='appointments', to='quickstart.contact')),
                ('resources', models.ManyToManyField(blank=True, related_name='appointments', to='quickstart.resource')),
            ],
            options={
                'db_table': 'crm_appointments',
                'ordering': ['-start_time'],
            },
        ),
    ]
