# Generated by Django 5.0.6 on 2025-09-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quickstart', '0146_contact_resource_appointment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentnote',
            name='student_not_user_id_be9394_idx',
        ),
        migrations.RemoveField(
            model_name='studentnote',
            name='user',
        ),
        migrations.AddField(
            model_name='studentnote',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['content_type', 'object_id'], name='student_not_content_e1a49d_idx'),
        ),
    ]
