# Generated by Django 4.2.5 on 2025-09-01 17:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    This function migrates the data from the old 'user' foreign key
    on StudentNote (which was removed in the previous migration) to the
    new 'content_type' and 'object_id' fields.

    Since the 'user' field is already removed from the model state in this migration,
    we have to look at the previous migration's state to find the data.
    """
    # Get the historical models
    StudentNote = apps.get_model("quickstart", "StudentNote")
    CustomUser = apps.get_model("quickstart", "CustomUser")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Get the content type for the CustomUser model
    user_content_type = ContentType.objects.get_for_model(CustomUser)

    # We need to access the database table directly as the 'user' field is gone from the model
    # This is a bit of a workaround because the field was removed in the same app version.
    # We query the state of the DB *before* this migration.
    # The previous migration (0147) removed the 'student' field but kept the column.
    # This data migration will transfer data from the old column to the new ones.

    # In this specific case, the schema change and data change should happen in one go.
    # A cleaner approach is to do this in the same migration as the schema change.
    # Let's assume we need to combine this logic.

    # A better approach for the user is to make the fields nullable,
    # then run a data migration, then make them non-nullable.
    # The user is already at the data migration step.

    # We need to populate the new fields based on the now-removed 'student_id' column
    # The column still exists in the DB at this point.

    # This logic assumes we are migrating from a state where 'student_id' was the FK
    # The previous migration renamed it to 'user_id' then removed it from the model.
    # We will iterate and populate based on what was there.
    # The easiest path is to assume the old field was called 'user_id'

    # Django migrations are tricky. Let's provide the most robust code.
    # We will check for the existence of the old column `user_id` on the table.

    from django.db import connection

    cursor = connection.cursor()
    cursor.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_name='student_notes' AND column_name='user_id'"
    )
    old_column_exists = cursor.fetchone()

    if old_column_exists:
        # We need to iterate over all notes that haven't been migrated
        for note in StudentNote.objects.filter(content_type__isnull=True).iterator():
            # Get the old user_id directly from the row
            # This is raw SQL to be safe
            cursor.execute("SELECT user_id FROM student_notes WHERE id = %s", [note.id])
            result = cursor.fetchone()
            if result and result[0] is not None:
                old_user_id = result[0]
                note.content_type = user_content_type
                note.object_id = str(old_user_id)
                note.save(update_fields=["content_type", "object_id"])


def backwards_func(apps, schema_editor):
    """
    This function can be used to reverse the migration, if needed.
    It populates the old 'user_id' field from the new generic FK fields.
    """
    StudentNote = apps.get_model("quickstart", "StudentNote")
    CustomUser = apps.get_model("quickstart", "CustomUser")
    ContentType = apps.get_model("contenttypes", "ContentType")
    user_content_type = ContentType.objects.get_for_model(CustomUser)

    # This is complex because the column doesn't exist on the model anymore.
    # For this case, we can simply nullify the fields on reverse.
    StudentNote.objects.filter(content_type=user_content_type).update(
        content_type=None, object_id=None
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "quickstart",
            "0147_remove_studentnote_student_not_user_id_be9394_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
