# Generated by Django 5.0.6 on 2025-09-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quickstart', '0148_migrate_studentnote_generic_fk_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
