# Generated by Django 5.0.6 on 2025-09-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0150_alter_contact_unique_together_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='cancellationCustomHours',
            field=models.PositiveIntegerField(blank=True, help_text="Custom cancellation notice period in hours, if policy is 'custom'.", null=True),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='cancellationPolicy',
            field=models.CharField(choices=[('flexible', 'Flexible (up to 1 hour before)'), ('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('strict', 'Strict (Non-refundable)'), ('custom', 'Custom Notice Period')], default='flexible', max_length=30),
        ),
    ]
