# Generated by Django 5.0.6 on 2025-09-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0151_classoption_cancellationcustomhours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_custom_hours',
            field=models.PositiveIntegerField(blank=True, help_text='The custom notice period in hours, snapshotted at time of booking.', null=True),
        ),
    ]
