# Generated by Django 5.0.6 on 2025-09-07 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0152_booking_cancellation_custom_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_schedule_instance',
            field=models.ForeignKey(blank=True, help_text='Stores the original instance if this booking was rescheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_bookings', to='quickstart.scheduleinstance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last reschedule action.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, help_text='The admin or staff who performed the reschedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
