# Generated by Django 5.0.6 on 2025-09-09 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0153_booking_is_rescheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Link to a CRM contact, used for guest bookings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='quickstart.contact'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['contact'], name='bookings_contact_ed77fc_idx'),
        ),
    ]
