# Generated by Django 5.0.6 on 2025-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0154_booking_contact_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_token',
            field=models.UUIDField(blank=True, db_index=True, help_text='Secure token for guest cancellations.', null=True, unique=True),
        ),
    ]
