# Generated by Django 5.0.6 on 2025-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0155_booking_cancellation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmain',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classesmain',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
