# Generated by Django 5.0.6 on 2025-09-16 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0156_classesmain_city_classesmain_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='minParticipants',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='scheduleinstance',
            name='min_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='classesmain',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
