# Generated by Django 5.0.6 on 2025-09-16 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0157_schedule_minparticipants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
