# Generated by Django 5.0.6 on 2025-09-16 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0158_alter_booking_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="widget_api_key",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Publicly-safe API key for the embeddable booking widget.",
                # Temporarily set null=True to allow adding the column to existing rows
                null=True,
                # The unique constraint will be added in a later migration
                unique=False,
            ),
        ),
    ]
