# Generated by Django 5.0.6 on 2025-09-16 08:31

import uuid
from django.db import migrations


def generate_uuids(apps, schema_editor):
    """
    Populates the widget_api_key field for all existing BusinessInfo
    instances with a unique UUID.
    """
    BusinessInfo = apps.get_model("quickstart", "BusinessInfo")
    for business in BusinessInfo.objects.all():
        business.widget_api_key = uuid.uuid4()
        business.save(update_fields=["widget_api_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0159_businessinfo_widget_api_key"),
    ]

    operations = [
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
    ]
