# Generated by Django 5.0.6 on 2025-09-16 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0160_populate_widget_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinfo",
            name="widget_api_key",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Publicly-safe API key for the embeddable booking widget.",
                # Now that all rows are populated, we can enforce uniqueness
                unique=True,
                # The field should not be nullable in its final state
                null=False,
            ),
        ),
    ]
