# Generated by Django 5.0.6 on 2025-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0161_alter_businessinfo_widget_api_key_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='allowed_widget_origins',
            field=models.JSONField(blank=True, default=list, help_text="A list of domains (e.g., 'www.mywebsite.com') where the widget is allowed to be embedded."),
        ),
    ]
