# Generated by Django 5.0.6 on 2025-09-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0162_businessinfo_allowed_widget_origins'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='theme',
            field=models.JSONField(blank=True, default=dict, help_text="Custom theming for the booking widget, e.g., {'primaryColor': '#0000FF', 'fontFamily': 'Georgia, serif'}."),
        ),
    ]
