# Generated by Django 5.0.6 on 2025-09-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0163_businessinfo_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessinfo',
            old_name='theme',
            new_name='widget_config',
        ),
    ]
