# Generated by Django 5.0.6 on 2025-09-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0164_rename_theme_businessinfo_widget_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcategory',
            options={'ordering': ['sort_order', 'name'], 'permissions': [('view_category_stats', 'Can view category statistics'), ('access_category_admin', 'Can access the Category Administration section')], 'verbose_name_plural': 'Class Categories'},
        ),
        migrations.AddField(
            model_name='classcategory',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Determines the display order; lower numbers appear first.'),
        ),
    ]
