# Generated by Django 5.0.6 on 2025-09-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0165_alter_classcategory_options_classcategory_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug. Auto-generated from the business name.', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='businessinfo',
            index=models.Index(fields=['slug'], name='business_in_slug_4e9e60_idx'),
        ),
    ]
