# Generated by Django

from django.db import migrations
from django.utils.text import slugify
import uuid


def generate_slugs_for_existing_businesses(apps, schema_editor):
    """
    Finds all BusinessInfo objects without a slug and generates a unique,
    URL-friendly slug from their businessName.
    """
    BusinessInfo = apps.get_model("quickstart", "BusinessInfo")
    db_alias = schema_editor.connection.alias

    existing_slugs = set(
        BusinessInfo.objects.using(db_alias)
        .exclude(slug__isnull=True)
        .exclude(slug__exact="")
        .values_list("slug", flat=True)
    )

    businesses_to_update = []
    for business in (
        BusinessInfo.objects.using(db_alias).filter(slug__isnull=True).iterator()
    ):
        base_slug = slugify(business.businessName) or "business"
        slug = base_slug
        while slug in existing_slugs:
            random_suffix = uuid.uuid4().hex[:6]
            slug = f"{base_slug}-{random_suffix}"
        business.slug = slug
        existing_slugs.add(slug)
        businesses_to_update.append(business)

    if businesses_to_update:
        BusinessInfo.objects.using(db_alias).bulk_update(businesses_to_update, ["slug"])
        print(
            f"\n  Successfully generated and saved slugs for {len(businesses_to_update)} businesses."
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "quickstart",
            "0166_business_slug_add_field",
        ),  # Dependency on the previous migration
    ]

    operations = [
        migrations.RunPython(
            generate_slugs_for_existing_businesses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
