# Generated by Django 5.0.6 on 2025-09-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0167_populate_business_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='slug',
            field=models.SlugField(help_text='SEO-friendly URL slug. Auto-generated from the business name.', max_length=255, unique=True),
        ),
    ]
