# Generated by Django 5.0.6 on 2025-09-30 19:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0169_alter_customuser_user_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedGoogleReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_review_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_avatar_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('owner_response', models.TextField(blank=True, null=True)),
                ('owner_response_date', models.DateTimeField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='Google', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_google_reviews', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'imported_google_reviews',
                'ordering': ['-review_date'],
            },
        ),
    ]
