# Generated by Django 5.0.6 on 2025-10-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0170_importedgooglereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedgooglereview',
            name='reviewer_avatar_url',
        ),
        migrations.AddField(
            model_name='importedgooglereview',
            name='reviewer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
