# Generated by Django 5.0.6 on 2025-10-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0171_remove_importedgooglereview_reviewer_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedgooglereview',
            name='reviewer_avatar',
        ),
    ]
