# Generated by Django 5.0.6 on 2025-10-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0172_remove_importedgooglereview_reviewer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgooglereview',
            name='reviewer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='public/reviews/'),
        ),
    ]
