# Generated by Django 5.0.6 on 2025-10-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0173_importedgooglereview_reviewer_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'permissions': [('toggle_business_feature', 'Can toggle the featured status for any business'), ('manage_business_staff', 'Can invite, remove, and manage staff for own business'), ('view_business_metrics', 'Can view aggregated business management statistics'), ('export_business_data', 'Can export business data as CSV'), ('send_business_announcements', 'Can send platform announcements to businesses'), ('access_business_admin', 'Can access the Business Administration section'), ('manage_own_classes', 'Can create/edit classes, options, schedules for own business'), ('manage_own_schedule_instances', 'Can manage instances (attendance, cancel) for own classes'), ('view_own_business_bookings', 'Can view bookings for own business'), ('manage_own_business_profile', 'Can edit own business profile details'), ('access_business_dashboard', 'Can access the dashboard for managing their own business'), ('view_business_revenue_analytics', 'Can view revenue analytics for own business'), ('export_business_revenue_data', 'Can export revenue data for own business'), ('view_business_students', 'Can view students associated with own business'), ('add_studentnote', 'Can add notes to students associated with own business'), ('view_studentnote', 'Can view notes for students associated with own business'), ('manage_business_roles', 'Can create, edit, and manage staff roles'), ('manage_own_business_discounts', 'Can create, edit, and manage discounts'), ('receive_booking_notifications', 'Can receive business notifications for new bookings and cancellations')], 'verbose_name_plural': 'Business Information'},
        ),
    ]
