# Generated by Django 5.0.6 on 2025-10-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0175_alter_businessrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgooglereview',
            name='reviewer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='originals/reviews/'),
        ),
    ]
