# Generated by Django 5.0.6 on 2025-11-07 01:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0176_alter_importedgooglereview_reviewer_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_group_id', models.UUIDField(db_index=True, help_text='Links all Booking records for this course', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active - In Progress'), ('completed', 'Completed Successfully'), ('cancelled', 'Cancelled Before Start'), ('dropped', 'Dropped Mid-Course')], default='pending', max_length=20)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid for the entire course', max_digits=10)),
                ('sessions_completed', models.PositiveIntegerField(default=0, help_text='Number of sessions the student has attended')),
                ('total_sessions', models.PositiveIntegerField(help_text='Total number of sessions in the course')),
                ('participants', models.IntegerField(help_text='Number of participants in this enrollment', validators=[django.core.validators.MinValueValidator(1)])),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_policy', models.CharField(max_length=30)),
                ('cancellation_custom_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellation_refund_percentage', models.PositiveIntegerField(default=100)),
            ],
            options={
                'db_table': 'course_enrollments',
                'permissions': [('view_course_analytics', 'Can view course analytics'), ('manage_course_enrollments', 'Can manage course enrollments')],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='course_session_number',
            field=models.PositiveIntegerField(blank=True, help_text='For courses: which session number (1, 2, 3...)', null=True),
        ),
        migrations.AddField(
            model_name='classoption',
            name='course_session_count',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated: Number of sessions in the course', null=True),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='booking_type',
            field=models.CharField(choices=[('Single Session', 'Single Session'), ('Full Course', 'Full Course')], default='Single Session', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_group_id', 'course_session_number'], name='bookings_booking_c3ea2e_idx'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='For guest enrollments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to='quickstart.contact'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='schedule',
            field=models.ForeignKey(help_text='The schedule that defines this course', on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='quickstart.schedule'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'status'], name='course_enro_user_id_070106_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['schedule', 'status'], name='course_enro_schedul_41f51b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['booking_group_id'], name='course_enro_booking_3adc0b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['enrollment_date'], name='course_enro_enrollm_7b95c1_idx'),
        ),
    ]
