# Generated by Django 5.0.6 on 2025-11-07 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0177_courseenrollment_booking_course_session_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='allowMidCourseDrops',
            field=models.BooleanField(default=False, help_text='If true, students can drop out after the course has started for a partial refund.'),
        ),
        migrations.AddField(
            model_name='classoption',
            name='midCourseCancellationCustomHours',
            field=models.PositiveIntegerField(blank=True, help_text='Custom notice period in hours for mid-course drops.', null=True),
        ),
        migrations.AddField(
            model_name='classoption',
            name='midCourseCancellationPolicy',
            field=models.CharField(blank=True, choices=[('flexible', 'Flexible (up to 1 hour before)'), ('24h', '24 Hours Notice'), ('48h', '48 Hours Notice'), ('72h', '72 Hours Notice'), ('strict', 'Strict (Non-refundable)'), ('custom', 'Custom Notice Period')], help_text='The cancellation policy that applies if a student drops mid-course.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='classoption',
            name='midCourseCancellationRefundPercentage',
            field=models.PositiveIntegerField(blank=True, help_text="Percentage of remaining sessions' value to be refunded for mid-course drops.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
