# Generated by Django 5.0.6 on 2025-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0178_classoption_allowmidcoursedrops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='scope',
            field=models.CharField(choices=[('business', 'Entire Business'), ('class', 'Entire Class'), ('schedule_group', 'Specific Schedule Group')], default='business', help_text='What this discount applies to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no start date.', null=True),
        ),
    ]
