# Generated by Django 5.0.6 on 2025-11-21 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0179_alter_discount_scope_alter_discount_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allocated_net_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The portion of the net payout allocated to this specific session.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('forfeited', 'Forfeited')], default='pending', max_length=20),
        ),
    ]
