# Generated by Django 5.0.6 on 2025-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0180_booking_allocated_net_payout_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='scheduleExpiryNotification',
            field=models.BooleanField(default=True, help_text='Receive warnings when classes are about to run out of scheduled instances.'),
        ),
    ]
