# Generated by Django 5.0.6 on 2025-12-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0181_businessinfo_scheduleexpirynotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='The code customers enter to get the discount. Leave blank for automatic discounts.', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together={('business', 'code')},
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['business', 'code'], name='quickstart__busines_aff9d6_idx'),
        ),
    ]
