# Generated by Django 5.0.6 on 2025-12-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0182_alter_discount_code_alter_discount_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short text for the homepage card')),
                ('image', models.ImageField(blank=True, null=True, upload_to='originals/collection_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order on homepage')),
            ],
            options={
                'db_table': 'class_collections',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classesmain',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Assign classes to curated vibes/collections (e.g. Date Night)', related_name='classes', to='quickstart.classcollection'),
        ),
    ]
