# Generated by Django 5.0.6 on 2025-12-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0183_classcollection_classesmain_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcollection',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='originals/collection_images/'),
        ),
    ]
