# Generated by Django 5.0.6 on 2025-12-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0184_alter_classcollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmain',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Assign classes to curated collections (e.g. Date Night)', related_name='classes', to='quickstart.classcollection'),
        ),
    ]
