# Generated by Django 5.0.6 on 2025-12-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0185_alter_classesmain_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcollection',
            name='automation_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classcollection',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual Curation'), ('automated', 'Automated (AI/Metrics)')], default='manual', max_length=20),
        ),
    ]
