# Generated by Django 5.2.8 on 2026-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0186_classcollection_automation_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='businessType',
            field=models.CharField(choices=[('individual', 'Individual Host'), ('tour-operator', 'Tour Operator'), ('experience-group', 'Experience Group'), ('venue', 'Venue / Studio'), ('event-organizer', 'Event Organizer'), ('school', 'School (Legacy)'), ('studio', 'Studio (Legacy)'), ('academy', 'Academy (Legacy)'), ('center', 'Learning Center (Legacy)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classoption',
            name='level',
            field=models.CharField(choices=[('no-experience', 'No Experience Needed'), ('beginner', 'Beginner Friendly'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('active', 'Moderate Physical Activity'), ('strenuous', 'Strenuous Activity'), ('all', 'Open to All Levels'), ('expert', 'Expert')], default='all', max_length=20),
        ),
    ]
