# Generated by Django 5.0.6 on 2026-01-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0188_map_legacy_business_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='description',
            field=models.TextField(blank=True, help_text='Specific details for this ticket tier.'),
        ),
        migrations.AddField(
            model_name='classoption',
            name='schedule_mode',
            field=models.CharField(choices=[('primary', 'Primary'), ('synced', 'Synced (Same Schedule)'), ('independent', 'Independent (Separate Schedule)')], default='primary', help_text='Determines if this tier follows the main schedule or has its own.', max_length=20),
        ),
        migrations.AddField(
            model_name='classoption',
            name='title',
            field=models.CharField(default='General Admission', help_text='Name of this ticket tier (e.g., VIP, General Admission).', max_length=150),
        ),
    ]
