# Generated by Django 5.0.6 on 2026-02-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0190_giftcard_giftcardtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='design_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
