# Generated by Django 5.0.6 on 2026-03-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0212_membershipproduct_badge_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_role', 'Can change the role assigned to any user'), ('lock_user', 'Can lock/unlock any user account'), ('reset_user_password', 'Can initiate password reset for any user'), ('view_user_metrics', 'Can view user management metrics'), ('access_user_admin', 'Can access the user administration section'), ('view_system_metrics', 'Can view real-time system performance metrics'), ('access_admin_dashboard', 'Can access the main platform administration dashboard'), ('access_blog_admin', 'Can access the Blog Management section'), ('access_global_discount_admin', 'Can access Global Discount management'), ('reply_own_support_ticket', 'Can reply to own support tickets'), ('cancel_own_booking', 'Can cancel their own booking'), ('add_supportticket', 'Can create new support tickets')]},
        ),
        migrations.RenameIndex(
            model_name='businessaddonsubscription',
            new_name='business_ad_busines_3fd4ec_idx',
            old_name='business_ad_busines_8b0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='customermembership',
            new_name='customer_me_product_a43b85_idx',
            old_name='customer_me_product_7a8c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='widgetsubscription',
            new_name='widget_subs_busines_ef7c5e_idx',
            old_name='widget_subs_business_status_idx',
        ),
        migrations.AlterField(
            model_name='classcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image displayed on the homepage category card.', max_length=255, null=True, upload_to='originals/category_images/'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_read_by_booker_at',
            field=models.DateTimeField(blank=True, help_text='Last time booker (guest) read the conversation.', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_read_by_business_at',
            field=models.DateTimeField(blank=True, help_text='Last time business side read the conversation.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('booking_cancelled_by_user', 'Booking Cancelled by User'), ('booking_cancelled_by_biz', 'Booking Cancelled by Business'), ('class_reminder_biz', 'Class Reminder for Business'), ('class_reminder_student', 'Class Reminder for Student'), ('new_review', 'New Review'), ('review_response', 'Review Response from Business'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('payout_initiated', 'Payout Initiated'), ('stripe_action_required', 'Stripe Action Required'), ('profile_incomplete', 'Profile Incomplete'), ('system_announcement', 'System Announcement'), ('new_message_support', 'New Message in Support Ticket'), ('new_message_chat', 'New Message in Conversation')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='conversationemaillog',
            index=models.Index(fields=['conversation', 'recipient_side'], name='conversatio_convers_daf69e_idx'),
        ),
    ]
