# Generated by Django 5.0.6 on 2026-03-28 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0215_membershipproduct_widget_cta_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaddonsubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='email_marketing_enabled',
            field=models.BooleanField(default=False, help_text='When True, business has an active email marketing addon (campaign sends).'),
        ),
        migrations.AddField(
            model_name='contact',
            name='marketing_unsubscribed',
            field=models.BooleanField(default=False, help_text="Opted out of this business's marketing emails (per-tenant CAN-SPAM)."),
        ),
        migrations.AddField(
            model_name='contact',
            name='marketing_unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BusinessMarketingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('physical_address_footer', models.TextField(blank=True, default='', help_text='Shown in marketing footer (CAN-SPAM). Defaults to business address if empty at send time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_settings', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'business_marketing_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailMarketingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(default='html', help_text='html | builder_json', max_length=32)),
                ('html_body', models.TextField(blank=True, default='')),
                ('builder_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_marketing_templates', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'email_marketing_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingSenderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('from_email', models.EmailField(help_text='Must match a verified sending domain for higher tiers; starter may use platform From.', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_sender_profiles', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'marketing_sender_profiles',
            },
        ),
        migrations.CreateModel(
            name='BusinessEmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', help_text='draft | scheduled | sending | sent | failed | cancelled', max_length=32)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('html_body', models.TextField(blank=True, default='')),
                ('builder_json', models.JSONField(blank=True, default=dict)),
                ('content_type', models.CharField(default='html', max_length=32)),
                ('audience_type', models.CharField(default='all_contacts', help_text='all_contacts | tags | contact_ids', max_length=64)),
                ('audience_filter', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='quickstart.businessinfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='quickstart.emailmarketingtemplate')),
                ('sender_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='quickstart.marketingsenderprofile')),
            ],
            options={
                'db_table': 'business_email_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingSendingDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('resend_domain_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='pending', help_text='pending | verified | failed', max_length=32)),
                ('dns_records', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_sending_domains', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'marketing_sending_domains',
            },
        ),
        migrations.CreateModel(
            name='BusinessMarketingUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('marketing_emails_sent', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_usage_periods', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'business_marketing_usage',
                'unique_together': {('business', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CampaignEmailSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('resend_email_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='quickstart.businessemailcampaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sends', to='quickstart.contact')),
            ],
            options={
                'db_table': 'campaign_email_sends',
                'indexes': [models.Index(fields=['campaign', 'to_email'], name='campaign_em_campaig_b838bd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignemailsend',
            constraint=models.UniqueConstraint(fields=('campaign', 'to_email'), name='uniq_campaign_email_send_recipient'),
        ),
        migrations.AddConstraint(
            model_name='marketingsendingdomain',
            constraint=models.UniqueConstraint(fields=('domain',), name='uniq_marketing_sending_domain_name'),
        ),
    ]
