# Generated by Django 5.0.6 on 2026-03-30 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0216_email_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSavedSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('audience_type', models.CharField(default='all_contacts', max_length=64)),
                ('audience_filter', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_saved_segments', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'marketing_saved_segments',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', help_text='draft | active | paused', max_length=32)),
                ('trigger_type', models.CharField(default='manual', help_text='manual | tag_added | booking_completed', max_length=64)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_workflows', to='quickstart.businessinfo')),
            ],
            options={
                'db_table': 'marketing_workflows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingWorkflowEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', help_text='active | completed | cancelled', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_enrollments', to='quickstart.contact')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quickstart.marketingworkflow')),
            ],
            options={
                'db_table': 'marketing_workflow_enrollments',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(help_text='delay | send_email', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='quickstart.marketingworkflow')),
            ],
            options={
                'db_table': 'marketing_workflow_steps',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketingworkflowenrollment',
            constraint=models.UniqueConstraint(fields=('workflow', 'contact'), name='uniq_workflow_enrollment_contact'),
        ),
    ]
