# Generated by Django 5.x migration

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0229_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedStripeEvent",
            fields=[
                ("event_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("event_type", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "processed_stripe_events",
            },
        ),
        migrations.CreateModel(
            name="StripeCheckoutAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("checkout_session_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("product_type", models.CharField(max_length=64)),
                ("plan_or_tier_key", models.CharField(blank=True, max_length=128)),
                ("stripe_price_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_checkout_attempts",
                        to="quickstart.businessinfo",
                    ),
                ),
            ],
            options={
                "db_table": "stripe_checkout_attempts",
            },
        ),
        migrations.AddIndex(
            model_name="stripecheckoutattempt",
            index=models.Index(fields=["business", "-created_at"], name="stripe_check_idx_business_created"),
        ),
    ]
