[supervisord]
nodaemon=true

[program:celery-worker]
command=celery -A CEBackend worker -l info
directory=/home/django/app
autostart=true
autorestart=true
startretries=3
stopsignal=TERM
user=django ; Run as the non-root user

[program:celery-beat]
command=celery -A CEBackend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/home/django/app
autostart=true
autorestart=true
startretries=3
stopsignal=TERM
user=django ; Run as the non-root user