[supervisord]
nodaemon=true                   ; Run supervisord in the foreground (essential for containers)
pidfile=/home/django/app/supervisord.pid ; Use a path the 'django' user can write to

; Redirect supervisord's own logs to stdout
logfile=/dev/stdout
logfile_maxbytes=0

[program:worker]
command=celery -A CEBackend worker --loglevel=INFO
directory=/home/django/app      ; Set the working directory
user=django                     ; Run as the non-root user
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
; Redirect worker logs to container's stdout/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:beat]
command=celery -A CEBackend beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/home/django/app
user=django
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
; Redirect beat logs to container's stdout/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0