[supervisord]
nodaemon=true
pidfile=/home/django/app/supervisord.pid
logfile=/dev/stdout
logfile_maxbytes=0

[program:worker]
# The correct flags for ElastiCache Serverless
command=celery -A CEBackend worker --loglevel=INFO --concurrency=1 --without-gossip --without-mingle
directory=/home/django/app
user=django
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:beat]
# These flags are not needed for beat, but we'll add them for consistency
command=celery -A CEBackend beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/home/django/app
user=django
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0