"""
Django settings for CEBackend project.
Generated by 'django-admin startproject' using Django 4.1.3.
"""

import os
import ssl
import sys
from datetime import timedelta
from pathlib import Path

# --- Environment Loading ---
# For containerized environments (like Docker), environment variables are passed
# directly by the orchestrator (e.g., via `docker run --env-file`).
# For local development without Docker, we load a .env file.
# The DJANGO_ENV variable controls which file is loaded locally.
IS_DOCKER = os.environ.get("IS_DOCKER") == "true"

if not IS_DOCKER:
    env_type = os.environ.get("DJANGO_ENV", "local")
    env_file = f".env.{env_type}"
    dotenv_path = Path(__file__).resolve().parent.parent / env_file
    if dotenv_path.exists():
        print(f"--- LOCAL: Loading environment variables from {dotenv_path} ---")
        from dotenv import load_dotenv

        load_dotenv(dotenv_path=dotenv_path)
    else:
        print(
            f"--- WARNING: .env file not found at {dotenv_path}. Relying on system environment variables. ---"
        )
else:
    print("--- DOCKER: Relying on environment variables passed to container. ---")


# --- Core Settings ---
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
DEBUG = os.environ.get("DEBUG", "False") == "True"
BASE_DIR = Path(__file__).resolve().parent.parent
USE_TZ = True
TIME_ZONE = "UTC"
SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "localhost:8000")
SITE_ID = 1
AUTH_USER_MODEL = "quickstart.CustomUser"
ROOT_URLCONF = "CEBackend.urls"
WSGI_APPLICATION = "CEBackend.wsgi.application"
ASGI_APPLICATION = "CEBackend.asgi.application"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Security & Network Settings ---
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", "http://localhost:5173"
).split(",")
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

IS_DEPLOYED_ENV = os.environ.get("DJANGO_ENV") in ["staging", "prod"]
COOKIE_DOMAIN = ".classeasily.com" if IS_DEPLOYED_ENV else None

# Secure cookie settings for deployed environments
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
SESSION_COOKIE_SECURE = IS_DEPLOYED_ENV
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_SECURE = IS_DEPLOYED_ENV
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # Must be False for JS to read the CSRF token
CSRF_COOKIE_SAMESITE = "Lax"

if IS_DEPLOYED_ENV:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# --- API & Service Keys ---
RESEND_API_KEY = os.environ["RESEND_API_KEY"]
GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_CLIENT_SECRET"]
STRIPE_PUBLIC_KEY = os.environ["STRIPE_PUBLIC_KEY"]
STRIPE_SECRET_KEY = os.environ["STRIPE_SECRET_KEY"]
STRIPE_WEBHOOK_SECRET = os.environ["STRIPE_WEBHOOK_SECRET"]
OPENROUTER_API_KEY = os.environ["OPENROUTER_API_KEY"]


# --- Installed Apps ---
INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "anymail",
    "storages",
    "channels",
    "silk",
    "quickstart.apps.QuickstartConfig",
]


# --- Middleware ---
# The order is critical for security and functionality.
MIDDLEWARE = [
    "quickstart.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "quickstart.middleware.JWTCookieMiddleware",
    "quickstart.monitoring.middleware.MetricsMiddleware",
]

# Conditionally enable Silk for performance profiling, but not during tests.
if "test" not in sys.argv:
    MIDDLEWARE.insert(2, "silk.middleware.SilkyMiddleware")


# --- Database (PostgreSQL) ---
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("DB_NAME", "CEDB"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "A>a*kU>)78P?$R)|k4Ae?|ramjpU"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# --- Caching & Channels (Redis) ---
CACHE_URL = os.environ.get("CACHE_URL", "redis://localhost:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [CACHE_URL]},
    },
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": (
                {"ssl_cert_reqs": ssl.CERT_NONE}
                if CACHE_URL.startswith("rediss://")
                else {}
            ),
        },
        "KEY_PREFIX": "classeasily",
    }
}


# --- Celery Configuration ---
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/1")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", "redis://localhost:6379/2"
)

CELERY_BROKER_TRANSPORT_OPTIONS = {
    # The hash tag "{celery}" ensures all keys go to the same slot.
    "global_keyprefix": "{celery}:",
    # Makes fanout (broadcast) operations cluster-safe.
    "fanout_prefix": True,
    "fanout_patterns": False,
    "visibility_timeout": 3600,
    "ack_emulation": False,
}

# This setting is CRITICAL for ElastiCache Serverless to prevent CROSSSLOT errors by disabling worker discovery.
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False

# Enable SSL for secure Redis connections ('rediss://')
if CELERY_BROKER_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}

# Common Celery settings
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True


# --- Authentication Backends ---
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    "quickstart.backends.RolePermissionBackend",
]


# --- REST Framework, Simple JWT, Dj-Rest-Auth ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/minute",
        "user": "100/minute",
        "burst": "150/minute",
        "sensitive": "5/minute",
        "chat": "30/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2000),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "AUTH_COOKIE_DOMAIN": COOKIE_DOMAIN,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_COOKIE": "my-app-auth",
    "AUTH_COOKIE_REFRESH": "my-refresh-token",
    "AUTH_COOKIE_DOMAIN": None,
    "AUTH_COOKIE_SECURE": IS_DEPLOYED_ENV,
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_SAMESITE": "Lax",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "userId",
    "USER_ID_CLAIM": "user_id",
}

FRONTEND_BASE_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")
FRONTEND_EMAIL_VERIFICATION_PATH = "/verify-email/{key}/"
FRONTEND_PASSWORD_RESET_CONFIRM_PATH = "/reset-password/{uid}/{token}/"

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,  # This must be False for dj-rest-auth's cookie flow
    "JWT_AUTH_COOKIE": "my-app-auth",
    "JWT_AUTH_REFRESH_COOKIE": "my-refresh-token",
    "JWT_AUTH_SAMESITE": "Lax",
    "OLD_PASSWORD_FIELD_ENABLED": True,
    "PASSWORD_RESET_CONFIRM_SERIALIZER": "dj_rest_auth.serializers.PasswordResetConfirmSerializer",
    "PASSWORD_RESET_USE_SITES_DOMAIN": False,
    "PASSWORD_RESET_CONFIRM_URL_PATH": FRONTEND_PASSWORD_RESET_CONFIRM_PATH,
    "USER_DETAILS_SERIALIZER": "quickstart.serializers.CustomUserDetailsSerializer",
}
REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "quickstart.serializers.CustomRegisterSerializer"
}
REST_AUTH_SERIALIZERS = {
    "LOGIN_SERIALIZER": "quickstart.serializers.CustomLoginSerializer"
}


# --- Allauth & Email ---
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/"
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@classeasily.com")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ANYMAIL = {"RESEND_API_KEY": RESEND_API_KEY}
SOCIALACCOUNT_ADAPTER = "quickstart.adapters.CustomSocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # Google already verifies emails
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": GOOGLE_CLIENT_ID,
            "secret": GOOGLE_CLIENT_SECRET,
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "VERIFIED_EMAIL": True,
    },
    "facebook": {
        "APP": {
            "client_id": "your-facebook-app-id",
            "secret": "your-facebook-app-secret",
            "key": "",
        }
    },
}


# --- Static & Media Files (AWS S3) ---
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-2")
AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "virtual"
DEFAULT_FILE_STORAGE = "quickstart.custom_storages.PrivateMediaStorage"
STATICFILES_STORAGE = "storages.backends.s3boto3.S3StaticStorage"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"


# --- Templates ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# --- Logging ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "quickstart": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
        "celery": {"handlers": ["console"], "level": "INFO"},
        "": {"handlers": ["console"], "level": "INFO"},
    },
}


# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# --- Internationalization ---
LANGUAGE_CODE = "en-us"
USE_I18N = True


# --- Silk (Performance Profiling) ---
SILKY_PYTHON_PROFILER_RESULT_PATH = os.path.join(
    BASE_DIR, "quickstart/monitoring/profiler"
)
SILKY_PYTHON_PROFILER = False
SILKY_PYTHON_PROFILER_BINARY = True
SILKY_AUTHENTICATION = False
SILKY_AUTHORISATION = False
SILKY_META = True
SILKY_INTERCEPT_PERCENT = 100
SILKY_MAX_RECORDED_REQUESTS = 10000
SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 10
SILKY_IGNORE_PATHS = ["/api/admin/metrics/"]


# --- Custom App Settings ---
# These are just examples; you can copy your actual settings here.
AI_SYSTEM_PROMPT = """You are ClassEasily Support Assistant..."""
CHAT_TERMINATION_INSTRUCTIONS = """CHAT TERMINATION..."""
NOTIFICATION_SETTINGS = {
    "default_from_email": DEFAULT_FROM_EMAIL,
    "default_from_name": "ClassEasily",
    "reply_to": "support@classeasily.com",
    "tracking": {"opens": True, "clicks": True},
    "max_batch_size": 1000,
    "rate_limit": 100,
}
