"""
Django settings for CEBackend project.
Generated by 'django-admin startproject' using Django 4.1.3.
"""

import os
import ssl
import sys
from datetime import timedelta

from django.template.exceptions import TemplateDoesNotExist
from celery.schedules import crontab
from pathlib import Path
import platform
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration


if os.name == "nt":  # This checks if the OS is Windows ('nt')
    GDAL_LIBRARY_PATH = r"C:\OSGeo4W\bin\gdal311.dll"
    GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"
    PROJ_LIBRARY_PATH = r"C:\OSGeo4W\bin\proj_9.dll"

if platform.system() == "Darwin":  # macOS
    GDAL_LIBRARY_PATH = "/opt/homebrew/opt/gdal/lib/libgdal.dylib"
    GEOS_LIBRARY_PATH = "/opt/homebrew/opt/geos/lib/libgeos_c.dylib"
    PROJ_LIBRARY_PATH = "/opt/homebrew/opt/proj/lib/libproj.dylib"

# --- Environment Loading ---
# For containerized environments (like Docker), environment variables are passed
# directly by the orchestrator (e.g., via `docker run --env-file`).
# For local development without Docker, we load a .env file.
# The DJANGO_ENV variable controls which file is loaded locally.
IS_DOCKER = os.environ.get("IS_DOCKER") == "true"
CLOUDFRONT_DOMAIN = os.environ.get("CLOUDFRONT_DOMAIN")

if not IS_DOCKER:
    env_type = os.environ.get("DJANGO_ENV", "local")
    env_file = f".env.{env_type}"
    dotenv_path = Path(__file__).resolve().parent.parent / env_file
    if dotenv_path.exists():
        print(f"--- LOCAL: Loading environment variables from {dotenv_path} ---")
        from dotenv import load_dotenv

        load_dotenv(dotenv_path=dotenv_path)
    else:
        print(
            f"--- WARNING: .env file not found at {dotenv_path}. Relying on system environment variables. ---"
        )
else:
    print("--- DOCKER: Relying on environment variables passed to container. ---")

# --- Core Settings ---
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
DEBUG = os.environ.get("DEBUG", "False") == "True"
BASE_DIR = Path(__file__).resolve().parent.parent
USE_TZ = True
TIME_ZONE = "UTC"
SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "localhost:8000")
SITE_ID = 1
SITE_NAME = "ClassEasily"
AUTH_USER_MODEL = "quickstart.CustomUser"
ROOT_URLCONF = "CEBackend.urls"
WSGI_APPLICATION = "CEBackend.wsgi.application"
ASGI_APPLICATION = "CEBackend.asgi.application"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Security & Network Settings ---
_allowed = os.environ.get(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,172.21.16.1"
).split(",")
# testserver: used by Django test client (e.g. cache prewarm in Celery worker)
ALLOWED_HOSTS = [h.strip() for h in _allowed] + ["testserver"]
CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", "http://localhost:3000"
).split(",")
REVALIDATION_SECRET = os.environ.get("REVALIDATION_SECRET")
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

IS_DEPLOYED_ENV = os.environ.get("DJANGO_ENV") in ["staging", "prod"]
COOKIE_DOMAIN = ".classeasily.com" if IS_DEPLOYED_ENV else None

SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
SESSION_COOKIE_SECURE = IS_DEPLOYED_ENV
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_SECURE = IS_DEPLOYED_ENV
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"

if IS_DEPLOYED_ENV:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = (
        os.environ.get("SECURE_SSL_REDIRECT", "False").lower() == "true"
    )
    SECURE_REDIRECT_EXEMPT = [r"^health-check/$", r"^$"]
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


def traces_sampler(sampling_context):
    # Don't send health checks to Sentry
    path = sampling_context.get("wsgi_environ", {}).get("PATH_INFO", "")
    if path == "/" or path == "/health-check/":
        return 0.0
    return 1.0


if IS_DEPLOYED_ENV and os.environ.get("SENTRY_DSN"):
    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        traces_sampler=traces_sampler,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        ignore_errors=[
            TemplateDoesNotExist,  # Ignore template errors
            "django.security.DisallowedHost",  # Ignore bots hitting with wrong IP/Host
        ],
        # Set to 1.0 to capture 100% of transactions for performance monitoring.
        # In high-traffic production, you might lower this to 0.1 or 0.2
        traces_sample_rate=1.0,
        send_default_pii=True,
        environment=os.environ.get("DJANGO_ENV"),
    )
# --- API & Service Keys ---
RESEND_API_KEY = os.environ["RESEND_API_KEY"]
GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_CLIENT_SECRET"]
STRIPE_PUBLIC_KEY = os.environ["STRIPE_PUBLIC_KEY"]
STRIPE_SECRET_KEY = os.environ["STRIPE_SECRET_KEY"]
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
# Secret for the endpoint at /api/webhooks/stripe-connect/
STRIPE_CONNECT_WEBHOOK_SECRET = os.environ.get("STRIPE_CONNECT_WEBHOOK_SECRET")

# Secret for the endpoint at /api/payments/webhook/
STRIPE_PAYMENTS_WEBHOOK_SECRET = os.environ.get("STRIPE_PAYMENTS_WEBHOOK_SECRET")
# Widget subscription. Set Stripe Price IDs to enable.
# Per-plan pricing: set WIDGET_SUBSCRIPTION_PRICE_BASIC, WIDGET_SUBSCRIPTION_PRICE_GROWTH,
# WIDGET_SUBSCRIPTION_PRICE_ADVANCED (each falls back to WIDGET_SUBSCRIPTION_PRICE_ID if unset).
# When WIDGET_SUBSCRIPTION_REQUIRED is True, the widget tab is locked until the business subscribes.
WIDGET_SUBSCRIPTION_PRICE_ID = os.environ.get("WIDGET_SUBSCRIPTION_PRICE_ID")
WIDGET_SUBSCRIPTION_PRICE_BASIC = os.environ.get("WIDGET_SUBSCRIPTION_PRICE_BASIC") or WIDGET_SUBSCRIPTION_PRICE_ID
WIDGET_SUBSCRIPTION_PRICE_GROWTH = os.environ.get("WIDGET_SUBSCRIPTION_PRICE_GROWTH") or WIDGET_SUBSCRIPTION_PRICE_ID
WIDGET_SUBSCRIPTION_PRICE_ADVANCED = os.environ.get("WIDGET_SUBSCRIPTION_PRICE_ADVANCED") or WIDGET_SUBSCRIPTION_PRICE_ID
WIDGET_SUBSCRIPTION_REQUIRED = os.environ.get("WIDGET_SUBSCRIPTION_REQUIRED", "False").lower() == "true"

# Marketplace email branding addon — $7/mo. Set MARKETPLACE_EMAIL_ADDON_PRICE_ID to Stripe Price ID.
MARKETPLACE_EMAIL_ADDON_PRICE_ID = os.environ.get("MARKETPLACE_EMAIL_ADDON_PRICE_ID")

OPENROUTER_API_KEY = os.environ["OPENROUTER_API_KEY"]
VERCEL_AUTOMATION_BYPASS_SECRET = os.environ["VERCEL_AUTOMATION_BYPASS_SECRET"]


# --- Installed Apps ---
INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.gis",
    "rest_framework_gis",
    "impersonate",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "anymail",
    "storages",
    "channels",
    "django_celery_beat",
    "quickstart.apps.QuickstartConfig",
]


# --- Middleware ---
# The order is critical for security and functionality.
MIDDLEWARE = [
    "quickstart.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "quickstart.middleware.DynamicCorsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "quickstart.middleware.SeoStagingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "quickstart.middleware.DisableCSRFForJWTMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "quickstart.middleware.JWTCookieMiddleware",
    "impersonate.middleware.ImpersonateMiddleware",
    "quickstart.monitoring.middleware.MetricsMiddleware",
]

# --- Database (PostgreSQL) ---
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}


# --- Caching & Channels (Redis) ---
DJANGO_ENV = os.environ.get("DJANGO_ENV", "local")

# LOG EVERYTHING
import sys

print(f"========== REDIS CONFIG DEBUG ==========", file=sys.stderr)
print(f"DJANGO_ENV: {DJANGO_ENV}", file=sys.stderr)
print(f"Raw CACHE_URL: {os.environ.get('CACHE_URL')}", file=sys.stderr)

# Get base URL - just remove any trailing database number if present
raw_url = os.environ.get("CACHE_URL", "redis://localhost:6379/0")
# Split by '/' and check if last part is a digit (database number)
parts = raw_url.split("/")
if len(parts) > 3 and parts[-1].isdigit():
    # Has a database number at the end, remove it
    CACHE_BASE = "/".join(parts[:-1])
else:
    # No database number, use as-is
    CACHE_BASE = raw_url

print(f"CACHE_BASE: {CACHE_BASE}", file=sys.stderr)

# Use different database numbers for staging vs prod
if DJANGO_ENV == "prod":
    CACHE_URL = f"{CACHE_BASE}/3"
    CELERY_BROKER_URL = f"{CACHE_BASE}/4"
    CELERY_RESULT_BACKEND = f"{CACHE_BASE}/5"
else:
    CACHE_URL = f"{CACHE_BASE}/0"
    CELERY_BROKER_URL = f"{CACHE_BASE}/1"
    CELERY_RESULT_BACKEND = f"{CACHE_BASE}/2"

print(f"Final CACHE_URL: {CACHE_URL}", file=sys.stderr)
print(f"Final CELERY_BROKER_URL: {CELERY_BROKER_URL}", file=sys.stderr)
print(f"Final CELERY_RESULT_BACKEND: {CELERY_RESULT_BACKEND}", file=sys.stderr)
print(f"========================================", file=sys.stderr)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [CACHE_URL]},
    },
}

# Use LocMem when DJANGO_ENV is local (no Redis required). Otherwise use Redis when CACHE_URL is set.
_use_redis_cache = DJANGO_ENV != "local" and bool(CACHE_URL)
if _use_redis_cache:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CACHE_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": (
                    {"ssl_cert_reqs": ssl.CERT_NONE}
                    if CACHE_URL.startswith("rediss://")
                    else {}
                ),
            },
            "KEY_PREFIX": "classeasily",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

CELERY_BROKER_TRANSPORT_OPTIONS = {
    "global_keyprefix": "{celery}:",
    # Makes fanout (broadcast) operations cluster-safe.
    "fanout_prefix": False,
    "fanout_patterns": False,
    "visibility_timeout": 3600,
    "ack_emulation": False,
}

CELERY_WORKER_ENABLE_REMOTE_CONTROL = False

# Enable SSL for secure Redis connections
if CELERY_BROKER_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}

# Common Celery settings
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_SEND_SENT_EVENT = False
CELERY_TASK_TRACK_STARTED = False

CELERY_BEAT_SCHEDULE = {
    "update-completed-bookings-daily": {
        "task": "quickstart.tasks.payout_tasks.update_completed_booking_status",
        "schedule": crontab(hour=2, minute=0),
    },
    "process-payouts-daily": {
        "task": "quickstart.tasks.payout_tasks.process_daily_payouts",
        "schedule": crontab(hour=3, minute=30),  # Staggered to 3:30 AM
    },
    "process-refunds-daily": {
        "task": "quickstart.tasks.payout_tasks.process_daily_refunds",
        "schedule": crontab(hour=5, minute=0),  # Staggered to 5:00 AM
    },
    "send-daily-review-requests": {
        "task": "quickstart.tasks.user_tasks.send_pending_review_requests",
        "schedule": crontab(hour=6, minute=30),  # Staggered to 6:30 AM
    },
    "send-hourly-booking-reminders": {
        "task": "quickstart.tasks.booking_tasks.send_upcoming_booking_reminders",
        "schedule": crontab(
            minute=15, hour="*"
        ),  # Run at :15 past every hour (avoids top of hour collision)
    },
    # "notify-expiring-schedules-weekly": {
    #     "task": "quickstart.tasks.business_tasks.notify_businesses_of_expiring_schedules",
    #     "schedule": crontab(day_of_week="monday", hour=9, minute=0), # Mondays at 9 AM UTC
    # },
    "release-expired-spots-every-5-min": {
        "task": "quickstart.tasks.booking_tasks.release_expired_spots",
        "schedule": crontab(minute="*/5"),  # Run every 5 minutes
    },
    "process-scheduled-gift-cards-daily": {
        "task": "quickstart.tasks.giftcard_tasks.process_scheduled_gift_cards",
        "schedule": crontab(hour=8, minute=0),
    },
    "generate-weekly-blog-draft": {
        "task": "quickstart.tasks.business_tasks.generate_weekly_blog_draft_task",
        "schedule": crontab(day_of_week=1, hour=10, minute=0),  # Monday 10:00 AM
    },
}

# Celery Worker Settings - Prevent prefetch issues
CELERYD_PREFETCH_MULTIPLIER = 1  # Worker only grabs 1 task at a time
CELERY_ACKS_LATE = True  # Don't acknowledge task until it's actually completed

# Use Django's LOGGING config in worker so task logs (e.g. prewarm) show at INFO
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# --- Blog AI (weekly draft generation) ---
BLOG_AI_ENABLED = True
BLOG_AI_DEFAULT_IMAGE_URL = "https://classeasily.com/images/blog-placeholder.jpg"
BLOG_AI_DEFAULT_CATEGORY_SLUG = "tips-and-guides"
BLOG_AI_DEFAULT_CATEGORY_NAME = "Tips & Guides"

# Email-specific settings
EMAIL_RATE_LIMIT_SETTINGS = {
    "RESEND_RATE_LIMIT": 2,  # requests per second
    "BATCH_SIZE": 10,  # emails per batch for bulk sending
    "RETRY_DELAY": 60,  # seconds to wait before retrying rate-limited requests
    "MAX_SUBJECT_LENGTH": 1900,  # characters (buffer below 2000 limit)
}

# --- Authentication Backends ---
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    "quickstart.backends.RolePermissionBackend",
]


# --- REST Framework, Simple JWT, Dj-Rest-Auth ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "500/minute",  # ← Increased from 100 to handle builds
        "user": "1000/minute",  # ← Increased from 200
        "burst": "300/minute",
        "sensitive": "25/minute",
        "chat": "30/minute",
        "widget": "120/minute",  # per X-Business-ID (widget embed)
    },
}

INTERNAL_IPS = [
    "172.21.31.174",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),  # Reduced from 2000 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_COOKIE": "my-app-auth",
    "AUTH_COOKIE_REFRESH": "my-refresh-token",
    "AUTH_COOKIE_DOMAIN": COOKIE_DOMAIN,  # CRITICAL: Must match
    "AUTH_COOKIE_SECURE": IS_DEPLOYED_ENV,
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_SAMESITE": "Lax",  # CRITICAL: Must be Lax
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "userId",
    "USER_ID_CLAIM": "user_id",
}

# Frontend base URL for revalidation, emails, redirects. When the backend runs in Docker or on
# a different host, set FRONTEND_URL to a URL reachable from the backend (e.g. your staging/prod
# frontend). Otherwise revalidation and other callbacks will try localhost:3000 and fail.
FRONTEND_BASE_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Meta Conversions API (CAPI) - server-side events with Pixel deduplication
# Only sends in production (DJANGO_ENV=prod). Set META_CAPI_ENABLED=true to override.
META_CAPI_ENABLED = os.environ.get("META_CAPI_ENABLED", "").lower() in ("1", "true") or (
    os.environ.get("DJANGO_ENV") == "prod"
)
META_PIXEL_ID = os.environ.get("META_PIXEL_ID", "")
META_CAPI_ACCESS_TOKEN = os.environ.get("META_CAPI_ACCESS_TOKEN", "")
# Optional: URL where the conversion happened (defaults to FRONTEND_BASE_URL or classeasily.com)
META_CAPI_EVENT_SOURCE_URL = os.environ.get(
    "META_CAPI_EVENT_SOURCE_URL", "https://www.classeasily.com"
)
# Optional: when set, events are sent as test events (visible in Events Manager > Test Events, do not affect reporting)
META_CAPI_TEST_EVENT_CODE = os.environ.get("META_CAPI_TEST_EVENT_CODE", "")

FRONTEND_EMAIL_VERIFICATION_PATH = "/verify-email/{key}/"
FRONTEND_PASSWORD_RESET_CONFIRM_PATH = "/reset-password/{uid}/{token}"
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "JWT_AUTH_COOKIE": "my-app-auth",
    "JWT_AUTH_REFRESH_COOKIE": "my-refresh-token",
    "JWT_AUTH_SAMESITE": "Lax",
    "OLD_PASSWORD_FIELD_ENABLED": True,
    "USER_DETAILS_SERIALIZER": "quickstart.serializers.CustomUserDetailsSerializer",
}
REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "quickstart.serializers.CustomRegisterSerializer"
}
REST_AUTH_SERIALIZERS = {
    "LOGIN_SERIALIZER": "quickstart.serializers.CustomLoginSerializer"
}


# --- Allauth & Email ---
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/"
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@classeasily.com")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ANYMAIL = {"RESEND_API_KEY": RESEND_API_KEY}
ACCOUNT_ADAPTER = "quickstart.adapters.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "quickstart.adapters.CustomSocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # Google already verifies emails
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": GOOGLE_CLIENT_ID,
            "secret": GOOGLE_CLIENT_SECRET,
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "VERIFIED_EMAIL": True,
    },
    "facebook": {
        "APP": {
            "client_id": "your-facebook-app-id",
            "secret": "your-facebook-app-secret",
            "key": "",
        }
    },
}


# --- Static & Media Files (AWS S3) ---
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-2")
AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "virtual"
# Django 5.0+: use STORAGES instead of DEFAULT_FILE_STORAGE / STATICFILES_STORAGE
STORAGES = {
    "default": {"BACKEND": "quickstart.custom_storages.PrivateMediaStorage"},
    "staticfiles": {"BACKEND": "storages.backends.s3boto3.S3StaticStorage"},
}
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"

# --- AWS SNS (SMS) ---
AWS_SNS_REGION = os.environ.get(
    "AWS_SNS_REGION",
    os.environ.get("AWS_S3_REGION_NAME", "us-east-2"),
)
AWS_SMS_ENABLED = os.environ.get("AWS_SMS_ENABLED", "false").lower() in ("true", "1")

# --- Templates ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# --- Logging ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "quickstart": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "celery": {"handlers": ["console"], "level": "INFO"},
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}


# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# --- Internationalization ---
LANGUAGE_CODE = "en-us"
USE_I18N = True


# --- Custom App Settings ---
# These are just examples; you can copy your actual settings here.
AI_SYSTEM_PROMPT = """You are ClassEasily Support Assistant..."""
CHAT_TERMINATION_INSTRUCTIONS = """CHAT TERMINATION..."""
NOTIFICATION_SETTINGS = {
    "default_from_email": DEFAULT_FROM_EMAIL,
    "default_from_name": "ClassEasily",
    "reply_to": "support@classeasily.com",
    "tracking": {"opens": True, "clicks": True},
    "max_batch_size": 1000,
    "rate_limit": 100,
}
