"""Typesense collection schema for public class search."""

CLASS_SEARCH_SCHEMA_BODY = {
    "fields": [
        {"name": "id", "type": "string"},
        {"name": "class_id", "type": "int32", "facet": False},
        {"name": "slug", "type": "string"},
        {"name": "title", "type": "string"},
        {"name": "description", "type": "string"},
        {"name": "business_name", "type": "string"},
        {"name": "business_state", "type": "string", "facet": True},
        {"name": "business_featured", "type": "bool", "facet": True},
        {"name": "location", "type": "geopoint"},
        {"name": "collection_slugs", "type": "string[]", "facet": True, "optional": True},
        {"name": "collection_paths", "type": "string[]", "facet": True, "optional": True},
        {"name": "option_tags", "type": "string[]", "facet": True, "optional": True},
        {"name": "booking_types", "type": "string[]", "facet": True, "optional": True},
        {"name": "min_price", "type": "float", "optional": True},
        {"name": "price_unknown", "type": "bool", "facet": True},
        {"name": "min_session_price", "type": "float", "optional": True},
        {"name": "min_course_price", "type": "float", "optional": True},
        {"name": "available_dates", "type": "string[]", "facet": True, "optional": True},
        {"name": "time_buckets", "type": "string[]", "facet": True, "optional": True},
        {"name": "weekdays", "type": "string[]", "facet": True, "optional": True},
        {"name": "max_capacity", "type": "int32"},
        {"name": "relevance_score", "type": "float"},
        {"name": "created_at_ts", "type": "int64"},
        {"name": "combined_avg_rating", "type": "float"},
        {"name": "combined_review_count_raw", "type": "int32"},
        {"name": "listing_duration_minutes", "type": "int32", "optional": True},
        {"name": "card_json", "type": "string"},
    ],
    "default_sorting_field": "relevance_score",
}
