name: Deploy Backend to Production

on:
  push:
    branches:
      - prod # Triggers ONLY on push to the 'prod' branch

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: classeasily-backend-staging
  ECS_CLUSTER: classeasily-prod-cluster
  ECS_SERVICE_WEB: classeasily-prod-web-service
  ECS_SERVICE_WORKER: classeasily-prod-worker-service
  ECS_TASK_DEFINITION: classeasily-prod-backend-task

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy to Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download existing task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json
      - name: Show task definition JSON
        run: |
          echo "--- Contents of task-definition.json ---"
          cat task-definition.json
          echo "------------------------------------"

      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: |
            web
            worker
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_WEB }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true # IMPORTANT: Waits for deployment to be stable

      - name: Update Worker Service
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_WORKER }} --task-definition ${{ steps.task-def.outputs.task-definition-arn }} --force-new-deployment
